#!/usr/bin/env node
// arxa-sidebar selftest — rows-world gate (docs/plans/sidebar-org-rethink.md):
//   1. manifest shape (repo plugin convention: dsh.client.inject + lib/client.js
//      UI half, lib/index.js server half, zero runtime dependencies)
//   2. composed client headers (gen-workspace + gen-sidebar, dsh 0.1.1-rc.2)
//   3. rows-world content: org store, OrgBrowser slot, locale relabels,
//      trash surface, shell New-session org-awareness; OrgSection GONE
//   4. drift gate: regenerate (shell + workspace transform) and byte-compare
//   5. both stock dsh packages byte-identical (content hashes)
//   6. registration wired (bin/arxa-studio.mjs + profile/cordis.patch.yml:
//      stock ui-sidebar AND ui-workspace disabled — one sidebar world active)
//   7. host half: rows state/action surface + lifecycle rows faces present
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync } from 'node:fs'
import vm from 'node:vm'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..', '..')
let failures = 0
const check = (label, ok, detail = '') => {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok || !detail ? '' : ` — ${detail}`}`)
  if (!ok) failures++
}

// ---- 1. manifest shape -------------------------------------------------------
const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'))
check('manifest: name', pkg.name === 'arxa-sidebar')
check('manifest: server half', pkg.main === 'lib/index.js')
check('manifest: client half exported', pkg.exports?.['./client'] === './lib/client.js')
check('manifest: cta-state export gone', pkg.exports?.['./cta-state'] === undefined)
check('manifest: dsh.client.inject declared', Array.isArray(pkg.dsh?.client?.inject)
  && pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-layout'))
check('manifest: platform web', pkg.dsh?.client?.platform === 'web')
check('manifest: zero runtime dependencies', !pkg.dependencies)

// ---- 2. composed client headers ----------------------------------------------
const client = readFileSync(join(here, 'lib', 'client.js'), 'utf8')
// D86 gate: the bundle must PARSE. A syntax error makes the app webview load
// client.js without it ever calling __ModuleLoader__.load ("Failed to load
// plugins") while every content grep below still passes. Compile-only, no exec.
let clientParseErr = ''
try { new vm.Script(client, { filename: 'lib/client.js' }) } catch (e) { clientParseErr = String(e) }
check('client.js parses (syntax error = unloadable sidebar)', !clientParseErr, clientParseErr)
const hostSrc = () => readFileSync(join(here, 'lib', 'index.js'), 'utf8')
check('headers: workspace part names its generator',
  client.includes('GENERATED by') && client.includes('scripts/gen-workspace.mjs from @deepseek-ai/dsh-client-ui-workspace'))
check('headers: shell part names its generator',
  client.includes('scripts/gen-sidebar.mjs'))
check('headers: client.js names dsh version', client.includes('0.1.1-rc.2'))
// 2026-09-03: Material file/folder glyphs in the org tree — the generated
// client carries the vendored-subset loader and both row injections.
check('icons: tree loader present', client.includes('function arxaIcons(') && client.includes('/__arxa/artifacts/vendor/icons.js'))
check('icons: file rows render material glyphs', client.includes('matIcons.file(name)'))
check('icons: dir rows render material folder glyphs (open/closed)', client.includes('matIcons.folder(sub'))
check('icons: stock dsh glyphs kept as fallback', client.includes('IconBrowseOutline16'))

// ---- 3. rows-world content ----------------------------------------------------
check('rows: org store present', client.includes('function createOrgStore()'))
check('rows: OrgBrowser is the slot component', client.includes('}, OrgBrowser));'))
check('rows: org data hooks pinned at the component boundary', client.includes('useWorkspaces: orgUseWorkspaces, useSessions: orgUseSessions') && client.includes('const orgUseWorkspaces = (sel) => useOrg'))
check('rows: honest content search (empty fetch)', client.includes('searchSessions: async () => ({ items: [], hasMore: false })'))
check('rows: trash surface wired (Q6)', client.includes('function TrashSection(') && client.includes('trash: () => orgStore.toggleTrash()'))
check('rows: locale relabels aboard', client.includes('"section.workspaces": "Organisations"'))
check('rows: stock Workspaces label superseded in overrides only', !client.includes('"section.workspaces": "Workspaces",\n\t\t\t\t"section.sessions"'))
check('rows: add flow opens the create-organisation modal (Q3, webview-safe)',
  client.includes('new Event("arxa-create-org")') && client.includes('function OrgCreateModal(') && client.includes('window.addEventListener("arxa-create-org", open)'))
check('create-modal: sign-in CTA carries the GitHub brand mark', client.includes('viewBox: "0 0 16 16"') && client.includes('d: GH_MARK'))
check('create-modal: D90 sign-in wall is GONE — submit always present, GitHub rides the switch', !client.includes('!showSignin && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Button, {') && !client.includes('showSignin') && client.includes('const canSubmit = name.trim() !== "" && !busy && location.trim() !== "" && !blocked;'))
check('create-modal: device-flow code surfaces in the sign-in step (github.device poll + big code)', client.includes('"github.device"') && client.includes('github.signin.codeHint') && client.includes('devCode.userCode'))
check('create-modal: D90 device-flow copy/open-link moved to the relink paths (purge + disconnect modals)', client.includes('open-external') && client.includes('https://github.com/login/device') && client.includes('devCode.userCode'))
check('rows: window.prompt is gone (Tauri WKWebView never implements it)', !client.includes('window.prompt('))
check('rows: location field opens the OS folder locator (Tauri dialog when injected, host osascript locator otherwise)',
  client.includes('window.__TAURI__.dialog') && client.includes('directory: true') && client.includes('pick-folder'))
check('host: macOS folder locator route exists', hostSrc().includes('choose folder') && hostSrc().includes('pick-folder'))
check('rows: first-run scaffolds into the picked folder or a subfolder named for the org (D77 supersedes in-place D69 — the PLATO incident)',
  client.includes('"org.create-at"') && (() => {
    const hostSrc = readFileSync(join(here, 'lib', 'index.js'), 'utf8')
    return hostSrc.includes("action === 'org.create-at'") && hostSrc.includes('shell.scaffoldOrg(target, nm)')
  })())
check('rows: org-level session creation is impossible (v2, grilled 2026-08-30) — the legacy + path is gone client AND host', !client.includes('\"org.new-session\"') && !hostSrc().includes("'org.new-session':"))
check('rows: OrgSection block deleted', !client.includes('OrgSection'))

// ---- 3b. workspace rows (org-model-v2 Phase C: D70/D71) ------------------------
check('rows-c: container rows (org/dock/project) own pseudo groups — a row survives its own collapse (v2 fix, 2026-08-30)',
  client.includes('function OrgContainerRow({ d, offset })') && client.includes('...ARXA_CONTAINER_ROWS(group.workspaceId)') && client.includes('offset: 4 + d.depth * 14 - host')
  && client.includes('...(ARXA_IS_CONTAINER_GROUP(group.workspaceId) ? [] : [(0, react_jsx_runtime.jsx)(ProjectRowItem, {')
  && client.includes('push(null, o.name)') && !client.includes('pendingRows') && !client.includes('WorkspaceRowsSection'))
check('rows-c: every container starts COLLAPSED (2026-08-30) — expansion is opt-in per row; no mount-time auto-expand',
  client.includes('if (!x[orgId]) return true;') && client.includes('const open = !!expandedMap[d.key];') && !client.includes('arxaAutoExpanded'))
check('rows-c: collapse hides descendants only — the org pseudo group never hides, leaves keep stable identity',
  client.includes('if (ws === "") return false;') && client.includes('ARXA_WS_HIDDEN(group.workspaceId)') && client.includes('emit[o.id] = [{ kind: "org"'))
check('rows-c: leaves are full stock workspace rows — indent by depth; collapse hides via display (identity never churns)',
  client.includes('ARXA_WS_INDENT(group.workspaceId)') && client.includes('ARXA_WS_HIDDEN(group.workspaceId)') && client.includes('toggleExpand(key)'))
check('rows-c: leaf click selects the workspace (composite id parse) — the ONLY startSession path',
  client.includes('ARXA_SELECT_WS(row.workspaceId)') && client.includes('workspace.new-session') && client.includes('const i = s.indexOf("|")'))
check('rows-c: shell CTA closes the loop (2026-09-01) — create then openCreated (session.open + conversation focus), never fire-and-forget',
  client.includes('w.openCreated(sel.orgId, b.result.id)') && client.includes('get ctaReady()') && client.includes('openCreated(orgId, sessionId)'))
check('rows-c: row "+" closes the loop too (found live 2026-09-02) — create → session.open → reveal → conversation focus, never create-and-stop',
  client.includes('orgStore.mutate("workspace.new-session", { orgId: s.slice(0, i), workspace: s.slice(i + 1) }).then((row) => {')
  && client.includes('orgStore.mutate("session.open", { orgId: s.slice(0, i), sessionId: row.id })')
  && client.includes('return arxaOpenConversation(row.id); });'))
check('crumbs: breadcrumb registered in the composer left zone too (2026-09-02) — the hero slot alone vanishes once a conversation opens',
  client.includes('ctx.slots.inject("conversation.input.left"') && client.includes('id: "arxa-crumbs"') && client.includes('}, ArxaCrumbBar));')
  && client.includes('function ArxaCrumbBar({ t })') && client.includes('if (current === void 0 || current === null) return null;'))
check('rows-c: CTA gate is DECLARATIVE — levers read at render; the imperative DOM gate is gone (it lost the re-render race)',
  client.includes('window.__ARXA_SIDEBAR__?.ctaReady !== true') && client.includes('window.__ARXA_SIDEBAR__?.ctaTitle ?? void 0') && !client.includes('useSessionCtaGate'))
check('rows-c: real session timestamps (the 56y bug fed ordinals as ages from 1970)',
  client.includes('x.updatedAt ?? x.createdAt ?? Date.now()') && !client.includes('updatedAt: order++'))
check('rows-c: rename rides the registry — one rename, every surface',
  client.includes('"session.rename"') && client.includes('renameSession: (sessionId, title)'))
check('rows-c: leaf-row ellipsis menu hidden (fixed folders are neither renamable nor deletable)',
  client.includes('false && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Menu, {'))
check('rows-c: scope gate — orgT capture keeps stock-scope render sites locale-safe',
  client.includes('let orgT =') && client.includes('orgT = props.t')
  && /function SessionTree\(\{[^)]*\bt\b[^)]*\)\s*\{/.test(client))
check('rows-c: OrgTreeSection dissolved', !client.includes('OrgTreeSection') && !client.includes('treeRows'))
check('rows-c: selection tooltip in all three locales', client.includes('"newSession.selectFirst": "Select a workspace to start a session"') && client.includes('"newSession.selectFirst": "Wybierz obszar roboczy, aby rozpocząć sesję"') && client.includes('"newSession.selectFirst": "Sélectionnez un espace de travail pour démarrer une session"'))
check('rows-c: server snapshot serves the per-org tree face + workspace-scoped sessions with real timestamps',
  hostSrc().includes('tree: treeOf(path)') && hostSrc().includes('workspace: s.workspace ?? null') && hostSrc().includes('createdAt: s.createdAt ?? null'))
check('rows-c: workspace.new-session takes a workspace path (loud on unknown); session.rename wired',
  hostSrc().includes("'workspace.new-session'") && hostSrc().includes('cur.newSession(undefined, ws)') && hostSrc().includes("'session.rename'"))

// ---- 3c. initial-snapshot gating (2025-08 create-org hang) ---------------------
// An in-place org root full of bulk content made the inline git add -A run
// for many minutes and froze the app mid-create. The contract now: create-at
// defers the snapshot (detached worker), the rows client gates the New
// Session CTA on the org's snapshotPending, and the message is human.
check('rows-snap: New Session CTA gates on the org-scoped selection + selected org snapshot state (all three locales)',
  client.includes('return !(o && o.open && o.snapshotPending === true);')
  && client.includes('orgT("newSession.snapshotPending")')
  && client.includes('"newSession.snapshotPending": "Preparing git snapshot — sessions unlock when it lands"')
  && client.includes('"newSession.snapshotPending": "Przygotowywanie migawki git — sesje odblokują się, gdy będzie gotowa"') && client.includes('"newSession.snapshotPending": "Préparation de l’instantané git — les sessions se débloqueront quand il sera prêt"'))
check('rows-snap: server snapshot exposes snapshotPending (open org)', hostSrc().includes('snapshotPending: cur?.path === path'))
check('rows-snap: create-at defers the initial snapshot (arxa-files-only history, fixed D92)', hostSrc().includes('deferSnapshot: true, includeExisting: false'))
check('rows-snap: host answers folder-info (a count only) for the create-time question', hostSrc().includes("'arxa-sidebar-folder-info'") && hostSrc().includes('entryCount'))
// ---- D111: the shell's new-session refusal is VISIBLE --------------------------
// Before this, the shell dropped a refusal twice over — a { ok:false } body fell
// out of the success `if` with no branch, and a throw died in a bare catch — so
// a red main read to the user as a dead button.
check('D111 shell: a !b.ok body is branched on, and the catch reports instead of swallowing',
  client.includes('if (!b || !b.ok) { notice(String((b && b.error) || "unknown")); return; }')
  && client.includes('.catch((e) => notice(String((e && e.message) || e)))')
  && !/action: "workspace\.new-session"[\s\S]{0,600}\}\)\.catch\(\(\) => \{\}\);/.test(client))
check('D111 shell: main-red renders a sentence in a shell-owned notice element',
  client.includes('"data-arxa-cta-notice": ctaNotice')
  && client.includes('ctaNotice === "main-red" ? t("session.new.err.mainRed") : ctaNotice')
  && client.includes('className: "aXa_sb_ctaNotice"'))
check('D111 shell: the notice auto-clears — every click dispatches a null code before the POST',
  client.includes('new CustomEvent("arxa-sidebar-notice", { detail: { code: null } })')
  && client.includes('const [ctaNotice, setCtaNotice] = (0, react.useState)(null);')
  && client.includes('window.addEventListener("arxa-sidebar-notice", onNotice)')
  && client.includes('return () => window.removeEventListener("arxa-sidebar-notice", onNotice)'))
check('D111 shell: the wording lives in the SHELL\'s own "sidebar" namespace (en+pl+fr), no arxa NS added',
  client.includes('"session.new.err.mainRed": "main is red — fix main before starting a session"')
  && client.includes('"session.new.err.mainRed": "main jest czerwony')
  && client.includes('"session.new.err.mainRed": "main est au rouge')
  && /ctx\.locale\.register\(NS, \{\n\t*zh,\n\t*en,\n\t*pl,\n\t*fr\n\t*\}\), "ui-sidebar: dictionaries"/.test(client))
check('D111 shell: the notice is styled with tokens only — no hex, no invented alias',
  /aXa_sb_ctaNotice\{[^}]*var\(--dsw-alias-state-error-primary\)[^}]*\}/.test(client)
  && !/aXa_sb_ctaNotice\{[^}]*#[0-9a-fA-F]{3,8}/.test(client))
// ---- Phase 4 A2/A4: the card is gone from this bundle ----------------------
// The git card (slides, CSS, locale, actions) lives in plugins/arxa-git-card;
// its selftest owns those cases. Here we only assert the seam holds.
check('A4: no git-card component, CSS or marker left in the sidebar bundle',
  ['ArxaGitCard', 'CARD_CSS', 'data-arxa-card', 'data-arxa-git-card', 'CHECK_STATE'].every((s) => !client.includes(s)))
check('A4: sidebar registers no conversation.input.dock entry (the card owns that strip)',
  !client.includes('conversation.input.dock'))
check('A4: no card.* / insight.* / version.* locale keys left in the sidebar dicts',
  !/"(card|insight|version)\.[A-Za-z.]+":/.test(client))
check('still no createPortal anywhere in the bundle', !client.includes('createPortal'))
check('create: D92 live preview + collision contract localized (en + pl + fr), snapshot radio deleted',
  client.includes('"org.create.preview": "Creates at"') && client.includes('"org.create.preview": "Utworzy w"') && client.includes('"org.create.preview": "Sera créée dans"') && client.includes('"org.create.exists.nonempty": "That folder already exists and isn\'t empty — change the name or the location."') && client.includes('"org.create.exists.nonempty": "Ten folder już istnieje i nie jest pusty — zmień nazwę lub lokalizację."') && client.includes('"org.create.exists.nonempty": "Ce dossier existe déjà et n’est pas vide — changez le nom ou l’emplacement."') && client.includes('"org.create.exists.open": "Open it instead"') && client.includes('"org.create.exists.open": "Otwórz ją zamiast tego"') && client.includes('"org.create.exists.open": "L’ouvrir à la place"') && !client.includes('org.create.existing') && !client.includes('includeExisting') && client.includes('folder-info'))
check('create: D92 engine target is ALWAYS root + slug(name); heuristic + includeExisting param deleted',
  hostSrc().includes('const target = path.join(expanded, nameSlug)') && !hostSrc().includes('pickedSlug') && hostSrc().includes("'folder-exists: '") && !hostSrc().includes('arg?.includeExisting'))
check('org.open: D92 by-path fallback is REACHABLE (awaited inside the try — a bare `return ensureOpen` skipped the catch)',
  hostSrc().includes('return await ensureOpen(ref)') && !hostSrc().includes('return ensureOpen(ref)'))
check('create: D92 sticky root + defaults action + open-by-path fallback',
  hostSrc().includes('create-root.json') && hostSrc().includes("'create.defaults'") && hostSrc().includes("fs.existsSync(ref + '/org.json')") && client.includes('ORG_POST("create.defaults")'))
check('rows-snap: create submit refreshes through the store (gate lifts at once, no create-again loop)', client.includes('orgStore.mutate("org.create-at"') && !client.includes('ORG_POST("org.create-at"'))
check('welcome: blank-page gate registers into the frame shell.overlay slot (Phase 2 — the fixed z-index war is gone)',
  client.includes('function WelcomeGate(') && client.includes('"welcome.title": "Welcome to arxa studio"')
  && client.includes('ctx.slots.inject("shell.overlay"') && client.includes('id: "arxa-welcome-gate",')
  && !client.includes('zIndex: 2147483000') && !client.includes('position: "fixed", inset: 0, zIndex'))
check('conformance: invented theme tokens are gone (text-critical/text-link/status-danger/text-secondary/bg-raised never existed)',
  !/dsw-alias-(text-critical|text-link|status-danger|text-secondary|bg-raised)/.test(client))
check('conformance: ErrorNote dedup — one shared error line across the org modals',
  client.includes('function ErrorNote({ msg })') && (client.match(/ErrorNote, \{ msg: /g) || []).length >= 5)
check('conformance: locale world is en/pl/fr — zhOver deleted, sparse plOver/frOver registered with per-key en fallback',
  client.includes('ctx.locale.register(NS, { zh, en: { ...en, ...enOver }, pl: plOver, fr: frOver })')
  && !client.includes('const zhOver = {') && client.includes('const plOver = {') && client.includes('const frOver = {'))
check('welcome: TWO buttons - arxa studio (create) + arxa business (disabled, later)', client.includes('t("welcome.studio")') && client.includes('t("welcome.business")') && client.includes('"welcome.businessSoon"') && !client.includes('t("welcome.cta")'))
check('welcome: one-shot resume to newest session of the open org', client.includes('resumeTried') && client.includes('maybeResume(next.orgs)') && client.includes('orgStore.mutate("session.open"'))
check('content area (2026-08-30): arxa is the sole driver — row open + resume focus the conversation via the client sessions service (dsh own open call)',
  client.includes('arxaOpenConversation(sessionId)') && client.includes('arxaOpenConversation(cand.id)') && client.includes('arxaClientSessions.open(dshId)') && client.includes('snap.ids.includes(dshId)'))
check('content area: a boot with nothing to resume clears the selection — stranding pre-arxa/hero sessions stop riding along',
  client.includes('arxaClientSessions.clear()') && client.includes('clearIfNothingToResume') && client.includes('let bootDecided = false;'))
check('content area: the boot clear SURVIVES dsh startup reconnect (workspaces.startInitialSelection re-opens the recent workspace blank session over an early clear) — bounded re-assert, org/user opens win',
  client.includes('reassertEmpty') && client.includes('workspaces.startInitialSelection') && client.includes('if (orgIds.has(cur)) return;') && client.includes('if (tries > 20) return;'))
check('content area (live, once-and-for-all): the rider kill is condition-driven, not a stopwatch — any current session that is not an OPEN org one is cleared on every store bump while no user/resume open owns the content (slow-boot stranding loses every race)',
  client.includes('enforceNoRiders') && client.includes('x.state === "open"') && client.includes('orgStore.refresh().then(enforceNoRiders)'))
check('content area (live): cross-client archive/rename reach every client without waiting on the 5s poll — the org view refreshes on dsh store bumps (sig-gated refresh makes repeats a no-op)',
  client.includes('ctx.get("workspaces").list.subscribe') && client.includes('arxaClientSessions.list.subscribe') && client.includes('orgStore.refresh()'))
check('content area: the hero workspace picker is replaced by arxa guidance (raw engine sessions cannot be born from the hero)',
  client.includes('ArxaHeroGuide') && client.includes('"conversation.hero.workspace"') && client.includes('"hero.guide": "Sessions start inside a workspace') && client.includes('"hero.guide": "Sesje zaczynają się wewnątrz obszaru roboczego') && client.includes('"hero.guide": "Les sessions démarrent dans un espace de travail'))
check('content area: with NOTHING bound the text composer is hidden outright (2026-08-30 user ask) — a bound blank session keeps its composer',
  client.includes('[data-arxa-empty] [data-slot=') && client.includes('data-arxa-empty') && client.includes('const unbound = current === void 0 || current === null;'))
// composer-resume-breadcrumb-sidebar-sync (grilled 2026-09-02, Q1–Q6)
check('Q1: the "sessions start…" guide renders ONLY when nothing is bound — a bound session shows the crumb instead',
  client.includes('if (unbound) return (0, react_jsx_runtime.jsxs)("div", {') && client.includes('const crumbs = arxaCrumbsFor(org, current) || [];'))
check('Q2: the hero row carries a read-only cordis crumb (org / dock / project / session / worktree) and the stock picker button is hidden in EVERY state',
  client.includes('"data-arxa-crumbs"') && client.includes('"aria-current": "location"') && client.includes('.wSkVaW_heroWorkspaceRow>button{display:none!important}') && !client.includes('[data-arxa-empty] .wSkVaW_heroWorkspaceRow>button'))
check('Q2: crumb grammar is the stock crumbs/crumbSeg/crumbSep/crumb/crumbCurrent tokens (label-tertiary middle, label-primary current, label-caption separators)',
  client.includes('[data-arxa-crumb]{display:block;max-width:220px;color:var(--dsw-alias-label-tertiary)') && client.includes('[data-arxa-crumb][data-current]{color:var(--dsw-alias-label-primary);font-weight:500}') && client.includes('[data-arxa-crumb-sep]{color:var(--dsw-alias-label-caption)'))
check('Q4: the crumb takes the free width; session + worktree segments never shrink',
  client.includes('[data-arxa-crumbs]{flex:1 1 auto;min-width:0') && client.includes('[data-arxa-crumb-seg][data-keep]{flex-shrink:0}'))
check('Q5 (corner, 2026-09-03): the preset chip lives INSIDE the composer card top-right — ArxaPresetCorner re-renders the stock seat entry on conversation.input.overlay (locale settings.agentPreset), the hero-row copy is hidden in EVERY state, no hero-row margin rule survives',
  client.includes('function ArxaPresetCorner({ slots, t })')
  && client.includes('name: "conversation.input.overlay"') && client.includes('id: "arxa-preset-corner"') && client.includes('locale: "settings.agentPreset"')
  && client.includes('slots.entriesOfSlot(PRESET_SEAT_KEY)[0]')
  && client.includes("[data-slot='conversation.hero.agentPreset']{display:none!important}")
  && client.includes('[data-arxa-preset-corner]{position:absolute;top:10px;right:14px;z-index:2}')
  && client.includes('.uV2eYG_root:not(.uV2eYG_hero) [data-arxa-preset-corner]{display:none}')
  && client.includes('padding-right:var(--arxa-preset-inset,120px)')
  && !client.includes("[data-arxa-empty] [data-slot='conversation.hero.agentPreset']")
  && !client.includes('.wSkVaW_heroWorkspaceRow>[data-slot=')
  && !client.includes('.wSkVaW_heroWorkspaceRow>:last-child{margin-left:auto'))
check('Q5 (revised): the hero row crumb is rendered once — bound hero returns a hidden anchor, the composer left zone owns the crumb',
  client.includes('"data-arxa-hero-anchor": ""') && !client.includes('return arxaCrumbNav(t, org, current, ref);'))
check('Q3 guard: the boot resume decision is made ONCE the org list settled — no-candidate branches set resumeTried, so a row created later via "+" is never opened with dropIfEmpty',
  (client.match(/if \(!state\.loading\) resumeTried = true;/g) || []).length === 2)
check('Q3: boot resume asks the host to drop a never-typed-in candidate and lands on the welcome hero when it did',
  client.includes('dropIfEmpty: true') && client.includes('if (r && r.dropped === true) {') && client.includes('return r ? r.result : void 0'))
check('Q6: opening/resuming a session reveals its row — ancestors expanded (never toggled), stock leaf group opened, row scrolled into view',
  client.includes('revealSession(sessionId) {') && client.includes('arxaViewActions = actions;') && client.includes('"data-session-id": node.id') && client.includes('el.scrollIntoView({ block: "nearest" })') && client.split('orgStore.revealSession(').length >= 4)
{
  const { readFileSync } = await import('node:fs')
  const lifecycle = readFileSync(new URL('../file-org-shell/lib/lifecycle.js', import.meta.url), 'utf8')
  const bridge = readFileSync(new URL('../file-org-shell/lib/dsh-bridge.js', import.meta.url), 'utf8')
  const hostSrc = readFileSync(new URL('./lib/index.js', import.meta.url), 'utf8')
  check('Q3 host: resumeSession(id, { dropIfEmpty }) drops ONLY on a positive "no user message" verdict (dsh doubt keeps the row) and archives the dsh side first',
    lifecycle.includes('async resumeSession(id, opts = {})') && lifecycle.includes('if (probe.ok && probe.value === false) {') && lifecycle.includes('await dshBridge.archive([row.dshSessionId])') && lifecycle.includes('dropSession(resolved, id, env)'))
  check('Q3 bridge: hasUserMessage is a throw-proof fifth face — non-boolean/throw/missing all read as dsh-unavailable',
    bridge.includes('async function hasUserMessage(id)') && bridge.includes("if (typeof out === 'boolean') return { ok: true, value: out }") && bridge.includes("out.ok === true && typeof out.value === 'boolean'") && bridge.includes('return { spawn, attach, retitle, list, archive, hasUserMessage }'))
  check('Q3 host face: live Session.events first, on-disk zstd log fallback, never a silent "empty"',
    hostSrc.includes('faces.hasUserMessage = async (id) =>') && hostSrc.includes("e.type === 'user/message'") && hostSrc.includes('readLogHasUserMessage(id)') && hostSrc.includes("'dsh-log-missing: '") && hostSrc.includes("dropIfEmpty: arg?.dropIfEmpty === true"))

  // ---- session-naming-agent-controls-and-cicd-card, stage 1 (2026-09-03) ----
  const sessionsSrc = readFileSync(new URL('../git-workspace/lib/sessions.js', import.meta.url), 'utf8')
  // Session identity was rewritten to a relative disk path (2026-09-03):
  // `nextSessionId` (bare leaf) is gone, superseded by `mintSessionPath`
  // (`<org folder>/<workspace key>/<word>-wt-<stamp>-<NNN>`).
  check('S1/Q2: the readable session id is minted from the workspace context, counter per path per day across words, with a taken-set skip',
    sessionsSrc.includes('export function mintSessionPath({ org, workspace, name, sessions, now = new Date() } = {}) {')
      && sessionsSrc.includes('const base = `${dir}/${word}-wt-${stamp}`')
      && sessionsSrc.includes('while (taken.has(base') && sessionsSrc.includes('taken.add(s.id)'))
  // Pinned as one contiguous block (not three independent .includes()) so a
  // refactor that moves `sessions: allSessions(...)` out of the
  // mintSessionPath({...}) call — leaving the substrings present elsewhere
  // in the file but the cross-registry wiring actually severed — still fails.
  check('S1/Q2: the mint reads the CROSS-REGISTRY aggregate — the id becomes the dsh session id, so uniqueness must span every repo',
    lifecycle.includes(`const sid = mintSessionPath({
            org: path.basename(resolved),
            workspace: ws,
            name,
            sessions: allSessions(resolved, env),
          })`))
  // Q9 supersedes Q3: the registry name now defaults to the LEAF of the id,
  // not the whole path — the breadcrumb already carries the folders, so a
  // row would otherwise read them twice. lifecycle.js passes the caller's
  // name through as `undefined` when empty; sessions.js's openSession does
  // the actual leaf default.
  check('S1/Q3->Q9: when the caller names nothing, the registry name DEFAULTS TO THE LEAF of the id (one display name everywhere)',
    lifecycle.includes("name: typeof name === 'string' && name.trim() !== '' ? name.trim() : undefined,")
      && sessionsSrc.includes('name: name || sessionLeaf(id),'))
  check('S1/Q3: the crumb collapses the duplicate tail — the session segment appears only once a rename diverges it from the worktree id',
    client.includes('if (!wt || nm !== wt) out.push({') && client.includes('const nm = row.name || row.id;'))
  check('S1/item1: the resolved preset id rides on meta so it lands in the session HEADER and the stock AgentPresetLabel lights up',
    hostSrc.includes('meta: { cwd, ...(presetId === undefined ? {} : { agentPreset: presetId }) }')
      && hostSrc.includes('const resolved = await presets.resolve(undefined)')
      && hostSrc.includes('setup = async (agentCtx) => { await presets.mount(agentCtx, resolved.id) }'))
  // Measured 2026-09-03: the AgentHandle carries NO `.session` (live=false in
  // the debug line), and rename() identity-checks against the store — so BOTH
  // paths must take the session from the store, never from the handle.
  // ---- stage 3: github sync + session-branch CI (2026-09-03) --------------
  const ghBridge = readFileSync(new URL('../file-org-shell/lib/github-bridge.js', import.meta.url), 'utf8')
  const ghLink = readFileSync(new URL('../github-link/lib/index.js', import.meta.url), 'utf8')
  const card = readFileSync(new URL('../arxa-git-card/lib/index.js', import.meta.url), 'utf8')
  check('S3/Q6: a push that fails on auth mints a FORCED token and retries once, then rethrows the ORIGINAL error',
    lifecycle.includes('async function pushWithAuthRetry(repoPath, repoUrl, kind')
      && lifecycle.includes('if (!AUTH_FAILURE_RE.test(String(err?.message ?? err))) throw err')
      && lifecycle.includes('await githubBridge.gitCredentials(true)')
      && ghBridge.includes('async function gitCredentials(force = false)')
      && ghLink.includes('async function gitCredentials(force = false)')
      && ghLink.includes('const accessToken = await getToken(force === true)'))
  check('S3/Q6: syncRepoNow no longer leaves a healed org reading publish-failed forever',
    lifecycle.includes('const clearStaleStatus = async ()')
      && lifecycle.includes("/^(publish-failed|sync-conflict|push-failed)/.test(st)")
      && lifecycle.includes("githubStatus: 'published'"))
  check('S3/Q6: the push path itself is routed through the retry — no bare pushRepo left in sync/publish',
    !lifecycle.includes('if (pushCreds.ok) pushRepo(') && !lifecycle.includes('if (c2.ok) pushRepo('))
  check('S3/Q6-Q7: a GREEN stage boundary publishes the session branch; a parked one does not, and the push never fails the commit',
    card.includes('if (out && out.parked === false)')
      && card.includes('out.pushed = await pushSessionBranch(gw, cur, sid).catch(')
      && card.includes('const pushSessionBranch = async (gw, cur, sid, { loud = false } = {})'))
  check('S3/Q8: checks are read for the BRANCH with or without a PR, and run control is wired',
    card.includes("const checks = await g.prChecks(manifest.repoOwner, manifest.repoName, s.branch)")
      && card.includes("'card.ci.rerun'") && card.includes("'card.ci.cancel'")
      && card.includes('g.rerunRun({ owner, name, runId') && card.includes('g.cancelRun({ owner, name, runId })'))
  // A project session's runs live in the PROJECT repo. This used to be handled
  // by REFUSING a project seat; it is now handled by targeting the right
  // repository, which is what the refusal was standing in for. The invariant
  // is unchanged and still the thing under test: a project seat must never act
  // on the org repo.
  check('S3/Q8: run control targets the SESSION`s repo, so a project seat never acts on the org',
    card.includes('const ciTarget = async () =>')
      && card.includes('const m = await repoFor(s)')
      && card.includes('return { g, owner: m.repoOwner, name: m.repoName, runId }')
      && !card.includes('project-session-pr-pending: run control'))
  check('S3/Q8: the PR handlers resolve the repo from the session, not from org.json',
    card.includes('const repoFor = async (s) =>')
      && card.includes("s?.origin === 'project' && typeof s?.repoPath === 'string'")
      && card.includes("s.repoPath + '/project.json'")
      && !card.includes('project-session-pr-pending: PR flow'))
  // The clear commit is made AFTER the ahead/behind read, so nothing upstream
  // pushes it — leaving it would swap a stale error for a repo permanently 1
  // ahead, the exact symptom being fixed.
  check('S3/Q6: the status-clearing commit is pushed, not left stranding main one ahead',
    lifecycle.includes('const clearStaleStatus = async () =>')
      && lifecycle.includes('if (committed !== null) await pushWithAuthRetry(repoPath, manifest.repoUrl, kind)')
      && (lifecycle.match(/await clearStaleStatus\(\)/g) || []).length === 3)
  check('S3/Q6-Q7: the boundary push tests the EXACT green value, so a return that omits parked cannot start pushing',
    card.includes('if (out && out.parked === false)') && !card.includes('out.parked !== true'))

  check('S1/Q1: the header title is PINNED to the worktree name on both spawn paths, throw-proof, from the STORE not the handle',
    hostSrc.includes('const pinTitle = (live) =>')
      && hostSrc.includes('svc.rename(live, name)')
      && !hostSrc.includes('pinTitle(handle && handle.session)')
      && (hostSrc.match(/pinTitle\(typeof sessions\.get === 'function' \? sessions\.get\(id\) : undefined\)/g) || []).length === 2)
}
check('empty state (2026-08-30 polish): guidance centered and spaced, arxa glyph in the hero lockup (brand plugin paints the mark, sidebar centers its slot)',
  client.includes('[data-arxa-empty] [data-arxa-hero-guide]{text-align:center') && client.includes('margin:12px auto 0') && !client.includes('textAlign: "left"'));

// ---- 4. drift gate ------------------------------------------------------------
// The committed client.js must equal shell+workspace regenerated, byte for
// byte. A hand-edit to client.js (or a stale snippet) goes RED here — fix the
// source (script/snippets), never the generated file. rc-bump policy lives in
// scripts/gen-workspace.mjs.
{
  const rootDir = join(here, '..', '..')
  const r = spawnSync(process.execPath, [join(rootDir, 'scripts', 'gen-workspace.mjs')], {
    cwd: rootDir, encoding: 'utf8', timeout: 60_000,
  })
  const regen = r.stdout ?? ''
  check('drift gate: client.js equals both transforms regenerated',
    r.status === 0 && regen === client,
    r.status === 0 ? 'byte drift — regenerate, or fix scripts/gen-*.mjs / snippets' : String(r.stderr).slice(0, 200))
}

// ---- 5. original dsh packages byte-identical ----------------------------------
// Parent-walk resolution: works from the main checkout AND from a git
// worktree nested under it (no node_modules of its own).
const hashPkg = (specifier, expected) => {
  const pkgDir = dirname(createRequire(import.meta.url).resolve(specifier + '/package.json'))
  const files = []
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const f = join(d, e.name)
      e.isDirectory() ? walk(f) : files.push(f)
    }
  }
  walk(pkgDir)
  const hash = createHash('sha256')
  for (const f of files) {
    hash.update(relative(pkgDir, f))
    hash.update('\0')
    hash.update(readFileSync(f))
    hash.update('\0')
  }
  const got = hash.digest('hex')
  return { got, ok: got === expected }
}
{
  const s = hashPkg('@deepseek-ai/dsh-client-ui-sidebar',
    '04d3a1afb6793bd9de0a26eb82b1266ecdf78da03899c5c32ac4258bf242c4e7')
  check('reference: dsh sidebar package byte-identical', s.ok, 'expected 04d3a1af…')
  const w = hashPkg('@deepseek-ai/dsh-client-ui-workspace',
    'db871ccc02577da5a5fe31420456b78ca390d40d2cc0a75322a120d218e810e3')
  check('reference: dsh workspace package byte-identical', w.ok, 'expected db871ccc…')
}

// ---- 6. registration wired ---------------------------------------------------
const bin = readFileSync(join(repo, 'bin', 'arxa-studio.mjs'), 'utf8')
check('registration: profile dependency (derived from the one PROFILE_PLUGINS list)',
  bin.includes("['arxa-sidebar', sidebarDir]") && /dependencies: Object\.fromEntries\(PROFILE_PLUGINS\.map/.test(bin))
check('registration: BY_NAME_PLUGINS', /BY_NAME_PLUGINS = \[[^\]]*'arxa-sidebar'/.test(bin))
check('registration: packed-mode copy list', bin.includes("['arxa-sidebar', sidebarDir]"))
const patch = readFileSync(join(repo, 'profile', 'cordis.patch.yml'), 'utf8')
check('registration: arxa-sidebar inserted', /id: arxa-sidebar\s*\n\s*name: arxa-sidebar/.test(patch))
check('registration: stock ui-sidebar disabled', /- id: ui-sidebar\s*\n\s*disabled: true/.test(patch))
check('registration: stock ui-workspace disabled (rows world owns the section)',
  /- id: ui-workspace\s*\n\s*disabled: true/.test(patch))

// ---- 7. host half + lifecycle rows faces --------------------------------------
const host = await import('./lib/index.js')
check('host: SEAM_LIFECYCLE_STUBBED declared', typeof host.SEAM_LIFECYCLE_STUBBED === 'boolean')
check('host: cta-state module gone', !readFileSync(join(here, 'lib', 'index.js'), 'utf8').includes('cta-state'))
let mod = null
try { mod = await import('arxa-file-org-shell') } catch {}
if (!mod) {
  try { mod = await import(new URL('../file-org-shell/lib/index.js', import.meta.url).href) } catch {}
}
check('seam: arxa-file-org-shell resolves with createOrgLifecycle', typeof mod?.createOrgLifecycle === 'function')
{
  // renameOrg is a verb ON an instance — build one against a throwaway root.
  const { mkdtempSync } = await import('node:fs')
  const os = await import('node:os')
  const svc = mod.createOrgLifecycle({ workspaceRoot: mkdtempSync(join(os.tmpdir(), 'arxa-rows-')), env: { ARXA_HOME: os.tmpdir() } })
  check('rows face: lifecycle exposes renameOrg (D41 manifest-only)', typeof svc.renameOrg === 'function')
}
{
  // The 2025-08 create-org hang, end-to-end against the REAL lifecycle on a
  // throwaway root: a deferred open leaves the snapshot pending (CTA-gated),
  // session creation refuses with a human reason, and the detached worker
  // lands HEAD on its own — the gate lifts itself without any caller waiting.
  const { mkdtempSync, mkdirSync, rmSync, writeFileSync } = await import('node:fs')
  const os = await import('node:os')
  const root = mkdtempSync(join(os.tmpdir(), 'arxa-snap-'))
  try {
    const orgPath = join(root, 'bulk-org')
    mkdirSync(orgPath, { recursive: true }) // D69: scaffold IN PLACE — the folder exists first
    // Real bulk: an empty fixture let the detached snapshot land before the
    // probe raced it (seen live 2026-08-30) — give the worker actual work so
    // \"pending\" holds long enough to observe.
    for (let i = 0; i < 400; i++) writeFileSync(join(orgPath, 'bulk-' + i + '.md'), 'bulk content\n')
    mod.scaffoldOrg(orgPath, 'Snap Org')
    // env is NOT optional here: openOrg → touchRecent inherits process.env
    // by default and would front-load this throwaway root into the REAL
    // ~/.arxa/organisation.json on every npm test run (seen live 2025-08:
    // eight dead arxa-snap-* entries squatting the user's recents).
    // The 400 files above were an attempt to make the snapshot slow enough to
    // observe; on a fast disk it still finished first and this block failed
    // for no reason of its own. Ask the worker to hold instead of guessing.
    const l2 = mod.createOrgLifecycle({ workspaceRoot: root, env: { ARXA_HOME: root, ARXA_SNAPSHOT_DELAY_MS: '4000' } })
    await l2.openOrg(orgPath, { deferSnapshot: true })
    check('rows-snap: deferred open reports snapshotPending true', l2.current.snapshotPending() === true)
    let guardMsg = ''
    try { await l2.current.newSession('probe', 'notes') } catch (e) { guardMsg = String(e?.message ?? e) }
    check('rows-snap: session creation refuses with a human reason while pending', guardMsg.includes('initial-snapshot-pending'))
    const deadline = Date.now() + 20000
    while (l2.current.snapshotPending() && Date.now() < deadline) await new Promise((r) => setTimeout(r, 100))
    check('rows-snap: detached snapshot lands HEAD; gate lifts itself', l2.current.snapshotPending() === false)
    try { l2.closeOrg() } catch {}
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}
check('rows face: host-served read-only exports (listSessions/listTrash)', typeof mod?.listSessions === 'function' && typeof mod?.listTrash === 'function')
check('rows face: workspace-root discovery exported', typeof mod?.loadWorkspaceRoot === 'function')

// ---- 8. pendingInteraction producer-consumer wiring (D63) ----------------------
// The producer is dsh itself: client-runtime SessionManager classifies
// question/requested mux frames into SessionSummary.pendingInteraction
// (approval | plan-review | question — 0.1.1-rc.2). The sidebar consumes it
// in three places; regeneration dropping any one silently strands the union
// (rows would never show the waiting pills), so pin all three.
check('wiring: session rows spread pendingInteraction',
  client.includes('...s.pendingInteraction === void 0 ? {} : { pendingInteraction: s.pendingInteraction }'))
check('wiring: search rows spread pendingInteraction',
  client.includes('...summary.pendingInteraction === void 0 ? {} : { pendingInteraction: summary.pendingInteraction }'))
check('wiring: status switch covers the closed union',
  client.includes('case "approval":') && client.includes('case "plan-review":')
  && client.includes('case "question":') && client.includes('assertNever(node.pendingInteraction)'))
check('wiring: runtime producer present (SessionManager pendingInteractions)',
  (() => {
    try {
      const rt = readFileSync(join(repo, 'node_modules', '@deepseek-ai', 'dsh-client-runtime', 'lib', 'client.js'), 'utf8')
      return rt.includes('pendingInteractions') && rt.includes('questionInteractionStatus')
    } catch { return false }
  })())

// ---- 9. D73/D74 github publish wiring ------------------------------------------
// The silent drop: getLifecycle built the lifecycle WITHOUT github faces, so
// the throw-proof stub answered github-unavailable for every publish while
// the account was linked (measured 2026-08-30 on TOPO project-001). Pin the
// exact injection expression, the manual-publish action, and the menu row.
check('github: the lifecycle is created WITH github faces injected (D73 root-cause fix)',
  hostSrc().includes('github: github ?? undefined'))
check('github: import failure degrades to the loud stub, never a crash',
  hostSrc().includes('await getGithub().catch(() => undefined)'))
check('github: manual publish action routes to the open-org handle (D74 hybrid heal)',
  hostSrc().includes("'github.publish'") && hostSrc().includes('cur.publishGithub()'))
check('github: org menu carries the connect verb (github.publish action survives)',
  client.includes('"github.publish"') && client.includes('{ id: "connect", label: orgT("menu.org.connect")'))
check('github: connect label localized (en + pl + fr)',
  client.includes('"menu.org.connect": "Connect to GitHub"') && client.includes('"menu.org.connect": "Połącz z GitHub"') && client.includes('"menu.org.connect": "Connecter à GitHub"'))

// ---- D77 (the PLATO incident): publish silence + placement trap ----
// The menu's publish row used to fire-and-forget (mutate().catch(() => {})):
// a refused publish (no HEAD, not linked) looked like NOTHING happened, and
// the create modal's location semantics made a volume ROOT the org (git init
// over the whole disk). Pin the redirect and the modal phase machine.
check('create-at: D92 target is ALWAYS picked-root/<slug(name)> — heuristic deleted',
  hostSrc().includes('const target = path.join(expanded, nameSlug)') && !hostSrc().includes('pickedSlug'))
check('create-at: the redirect reuses the real slugify (no drift from D41 slugs)',
  hostSrc().includes("import(new URL('../../workspace/lib/slug.js', import.meta.url).href)"))
check('create-at: an org name with no slug fails loud before any disk write',
  hostSrc().includes("'org name has no slug: '"))
check('publish: the menu row dispatches the modal event (no swallowed mutate)',
  client.includes('"arxa-publish-org"') && !client.includes('orgStore.mutate("github.publish"'))
check('publish: modal runs the phase machine over the publish result',
  client.includes('function OrgPublishModal') && client.includes('target.projectSlug ? "project.connect" : "github.publish"') && client.includes('initial-snapshot-pending'))
check('publish: modal localized (en + pl + fr)',
  client.includes('"publish.confirmCta": "Publish"') && client.includes('"publish.confirmCta": "Opublikuj"') && client.includes('"publish.confirmCta": "Publier"'))

// ---- D79: GitHub-parity labels + named project creation (D78 riders) ----
// v3 containers carry their stage prefix on GitHub ("00-moodboard"); the
// tree shows the SAME real directory name. Only a genuine dictionary hit
// (a pre-v3 folder like "moodboard") prettifies — no stem mapping, no
// TitleCase, and never a leaked raw tree.pc key.
check('labels: stage containers render their real directory name (GitHub parity)',
  client.includes('const hit = orgT("tree.pc." + c);') &&
  client.includes('if (hit && hit !== "tree.pc." + c) return hit;') &&
  client.includes('return c;') &&
  !client.includes('stemHit') && !client.includes('const stem ='))
check('project create: the dock + opens a NAME modal (no pregenerated names in the UI)',
  client.includes('"arxa-create-project"') && client.includes('function OrgProjectModal') && !client.includes('orgStore.mutate("project.create"'))
check('project create: modal sends the typed name through project.create',
  client.includes('ORG_POST("project.create", { orgId: target.orgId, name: n })'))
check('project create: modal localized (en + pl + fr)',
  client.includes('"project.create": "Create project"') && client.includes('"project.create": "Utwórz projekt"') && client.includes('"project.create": "Créer le projet"'))

// ---- D80: row menus, the rename ride, the Trash row ----
check('menus: ONLY org + project rows carry the kebab (docks/containers never)',
  client.includes('const showMenu = isOrg || d.kind === "project";') && client.includes('showMenu && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Menu, {') && !client.includes('isOrg && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Menu'))
check('menus: org Rename + project Rename/Trash items',
  client.includes('"menu.org.rename"') && client.includes('"menu.project.rename"') && client.includes('"menu.project.trash"') && !client.includes('id: "trash", label: orgT("menu.trash")'))
check('rename: the modal drives org.rename and project.rename',
  client.includes('function OrgRenameModal') && client.includes('ORG_POST("org.rename"') && client.includes('ORG_POST("project.rename"'))
check('rename: events wired both directions',
  client.includes('"arxa-rename-org"') && client.includes('"arxa-rename-project"') && client.includes('window.addEventListener("arxa-rename-org", onRenameOrg)') && client.includes('window.addEventListener("arxa-rename-project", onRenameProject)'))
check('trash: a permanent divider row with count badge + empty state (en + pl + fr)',
  client.includes('function TrashSection') && client.includes('borderTop: "1px solid var(--dsw-alias-border-l2') && client.includes('"trash.empty": "Trash is empty"') && client.includes('"trash.empty": "Kosz jest pusty"') && client.includes('"trash.empty": "La corbeille est vide"') && !client.includes('if (rows.length === 0 || !view.open) return null;'))
check('routes: project.rename drives the full-move machinery; project.trash parks locally',
  hostSrc().includes("'project.rename'") && hostSrc().includes('l.renameProject(cur.path, arg.projectSlug, arg.name)') && hostSrc().includes("'project.trash'") && hostSrc().includes('cur.trashProject(arg.projectSlug)'))

// ---- D81: the org itself is trashable; Delete forever really deletes ----
check('purge: the modal drives orgtrash.purge and projecttrash.purge',
  client.includes('function OrgPurgeModal') && client.includes('"orgtrash.purge" : "projecttrash.purge"'))
check('purge: the trash row dispatches the confirmation event',
  client.includes('"arxa-purge-trash"') && client.includes('window.addEventListener("arxa-purge-trash", onPurge)'))
check('trash: org group + delete-forever + project group (localized en + zh)',
  client.includes('"trash.orgSection": "Organisations"') && client.includes('"trash.orgSection": "Organizacje"') && client.includes('"trash.projectSection": "Projects"') && client.includes('"trash.projectSection": "Projekty"') && client.includes('"trash.projectSection": "Projets"') && client.includes('"trash.deleteForever": "Delete forever"') && client.includes('"trash.deleteForever": "Usuń na zawsze"') && client.includes('"trash.deleteForever": "Supprimer définitivement"'))
check('routes: org trash/restore/purge wired to the service faces',
  hostSrc().includes("'org.trash'") && hostSrc().includes('l.trashOrg(orgByRef(arg?.orgId).path)') && hostSrc().includes("'orgtrash.restore'") && hostSrc().includes('l.restoreOrg(arg?.entryId)') && hostSrc().includes('l.purgeOrgTrash(arg.entryId)') && hostSrc().includes('cur.purgeTrash(arg.entryId)'))

// ---- D82: org-menu Move to Trash + design-system trash surface ----
check('menus: org menu REGAINS Move to Trash (danger) dispatching org.trash',
  client.includes('id: "trash", label: orgT("menu.org.trash")') && client.includes('orgStore.mutate("org.trash", { orgId: d.orgId })') && client.includes('"menu.org.trash": "Move to Trash"') && client.includes('"menu.org.trash": "Przenieś do Kosza"') && client.includes('"menu.org.trash": "Déplacer vers la corbeille"'))
check('menus: every row-menu item carries a design-system glyph (edit/folder/github/trash)',
  client.includes('IconEditOutline16') && client.includes('icon: ghMark16') && client.includes('IconTrashOutline16, {}), danger: true }'))
check('menus: D87 close is GONE (unscoped verb — opening another org already switches)',
  !client.includes('id: "close"') && !client.includes('menu.org.close') && !client.includes('IconCloseOutline16'))
check('trash: header rides the tree-row chevron (arrow/arrowOpen) — no text glyph',
  client.includes('IconTriangleRightFill14, { className: clsx(Rows_module_css_default.arrow, open && Rows_module_css_default.arrowOpen) })') && !client.includes('children: "▶"'))
check('trash: entries use rowActions icon buttons under Tooltips (restore=refresh, delete=trash in critical ink)',
  client.includes('.Tooltip, {') && client.includes('IconRefreshOutline16, onRestore') && client.includes('IconTrashOutline16, onPurge, true') && client.includes('className: Rows_module_css_default.iconButton'))
check('trash: auto-opens while anything is trashed; manual toggle wins',
  client.includes('const [manual, setManual] = (0, react.useState)(null);') && client.includes('const open = manual === null ? total > 0 : manual;'))
check('trash: org glyph shared between tree row and trash org entries (single def)',
  client.includes('function OrgGlyph({ size })') && client.split('function OrgGlyph({ size })').length === 2 && client.includes('entryRow(e, (0, react_jsx_runtime.jsx)(OrgGlyph, {}), () => restoreOrg'))
// ---- D83: trash lives under the last org row; icons keep their spacing ----
check('trash: rides the grouped tree tail via ARXA_TRASH_AFTER_ORGS (no bottom mount)',
  client.includes('const ARXA_TRASH_AFTER_ORGS = () => orgT ? (0, react_jsx_runtime.jsx)(TrashSection, { t: orgT, key: "arxa-trash" }) : null;') && client.includes('}), ARXA_TRASH_AFTER_ORGS()]') && !client.includes('TrashSection, { t: props.t }'))
// ---- T4 v2 (2026-09-01, user direction): files live INSIDE the tree under the owning row ----
check('files: NO separate tail section — ArxaFilesSection/ARXA_FILES_AFTER_ORGS are gone',
  !client.includes('ARXA_FILES_AFTER_ORGS') && !client.includes('ArxaFilesSection'))
check('files: ArxaDirRows mounts inline on container rows (files-only — their dirs are already tree containers)',
  client.includes('function ArxaDirRows') && client.includes('mode: "files-only"') && client.includes('d.kind === "dock" ? d.slug : "projects/" + d.slug'))
check('files: leaf worktrees list their content in place (ARXA_LEAF_FILES, full mode, dirs expandable)',
  client.includes('ARXA_LEAF_FILES(group),') && client.includes('mode: "full"') && client.includes('if (ARXA_IS_CONTAINER_GROUP(group.workspaceId)) return null;'))
check('files: lazy tree route + one fresh-token 403 retry + arxa-av-open bridge unchanged',
  client.includes('"/__arxa/artifacts/tree?dir="') && client.includes('scope: "tree-read"') && client.includes('window.dispatchEvent(new CustomEvent("arxa-av-open", { detail: { relPath } }))'))
check('files: expanding an org row opens the org (tree-read rides the open handle) + human hint when it is not open',
  client.includes('if (isOrg && !open) orgStore.mutate("org.open", { orgId: d.orgId }).catch(() => {});') && client.includes('/no org open/i.test(entry.error || "")') && client.includes('"files.openHint": "Open this organisation to browse its files"') && client.includes('"files.openHint": "Otwórz tę organizację, aby przeglądać jej pliki"') && client.includes('"files.openHint": "Ouvrez cette organisation pour parcourir ses fichiers"'))
check('trash: restore/delete icon buttons are gapped (flex span, 12px user-tuned)',
  client.includes('style: { display: "flex", gap: 12, flex: "none", alignItems: "center" }, children: [') && client.includes('IconRefreshOutline16, onRestore),') && client.includes('IconTrashOutline16, onPurge, true)'))
// ---- D84: the trash reads exactly like the tree above it ----
check('trash: header row IS an org row (projectRow class, treeitem, 600 weight, no kebab)',
  client.includes('style: { marginLeft: 4, marginTop: 4, borderRadius: 6, cursor: "pointer", fontWeight: 600 }') && client.includes('"aria-expanded": open,') && client.includes('className: Rows_module_css_default.title, children: t("trash.section")') && !client.includes('borderRadius: 8, padding: "0 6px"'))
check('trash: header count is the plain org-row count (11px, no pill)',
  client.split('fontSize: 11, opacity: 0.55, flex: "none", marginRight: 4').length === 3)
check('trash: entries are stock project rows at the depth-1 margin (18px, 14px title class)',
  client.includes('style: { marginLeft: 18, marginTop: 2, cursor: "default" }') && client.includes('className: Rows_module_css_default.projectText, children: (0, react_jsx_runtime.jsx)("span", { className: Rows_module_css_default.title, title: e.entryId'))
check('trash: group labels are glyph-free 10px captions (no uppercase TRASHED wording anywhere)',
  client.includes('fontSize: 10, lineHeight: "16px", letterSpacing: "0.06em"') && client.includes('groupLabel(t("trash.orgSection"))') && !client.includes('groupLabel((0, react_jsx_runtime.jsx)(') && !client.includes('Trashed'))
// ---- D85: the 403 delete_repo dead-end upgrades itself ----
check('purge: the scope-stale 403 offers re-link & retry in the modal (device flow inline)',
  client.includes('errMsg.includes("re-link GitHub") && !relinking') && client.includes('onClick: relink') && client.includes('const relink = () => {') && client.includes('ORG_POST("github.link").then(() => {'))
check('purge: the re-link surfaces the one-time code and AUTO-retries the same purge',
  client.includes('ORG_POST("github.device").then((r) => {') && client.includes('if (d && d.userCode) setDevCode(d);') && client.includes('children: devCode.userCode') && client.includes('setRelinking(false); setDevCode(null);\n\t\t\t\t\tsubmit();'))
check('purge: re-link strings localized (en + pl + fr)',
  client.includes('"purge.relink": "Re-link GitHub & retry"') && client.includes('"purge.relink": "Połącz ponownie z GitHub i ponów"') && client.includes('"purge.relink": "Re-lier GitHub et réessayer"') && client.includes('"purge.relinkHint"'))
// ---- D88: ghost-row sync fix + GitHub-style typed delete gate ----
check('store: orgTrash rides the change signature (purge-only mutations must land)',
  client.includes('next.orgTrash, next.trashCount'))
check('purge: D88 typed-name gate arms Delete forever (exact, case-sensitive row label)',
  client.includes('const matches = typed === target.name;') && client.includes('disabled: !matches || phase === "busy"') && client.includes('t("purge.typeName").replace("{name}", target.name)') && client.includes('placeholder: target.name'))
check('purge: D88 busy LOCK (Close dead while deleting) + retry + auto-close + summary',
  client.includes('variant: "outline", disabled: phase === "busy", onClick: dismiss') && client.includes('t("purge.retry")') && client.includes('setTimeout(onClose, 1100)') && client.includes('res.deletedRepos.join(", ")'))
check('purge: D88 typed gate + retry localized (en + pl + fr)',
  client.includes('"purge.typeName": "Type {name} exactly to confirm."') && client.includes('"purge.typeName": "Wpisz dokładnie {name}, aby potwierdzić."') && client.includes('"purge.typeName": "Saisissez {name} exactement pour confirmer."') && client.includes('"purge.retry": "Try again"') && client.includes('"purge.retry": "Spróbuj ponownie"') && client.includes('"purge.retry": "Réessayer"'))
// ---- D90: link/unlink GitHub per org + project; local-only creation ----
check('menus: D90 connect/disconnect replaces publish — state-dependent per org + project',
  client.includes('d.connected === false ? { id: "connect", label: orgT("menu.org.connect"), icon: ghMark16 } : { id: "disconnect", label: orgT("menu.org.disconnect"), icon: ghMark16 }') && client.includes('d.connected === false ? { id: "connect", label: orgT("menu.project.connect"), icon: ghMark16 }') && client.includes('"arxa-disconnect-github"') && !client.includes('menu.org.publish'))
check('rows: D91 connected marker (GitHub mark on CONNECTED rows only) + connected flags ride org and project rows',
  client.includes('connected: !!o.connected') && client.includes('connected: !!p.connected') && client.includes('d.connected === true ?') && client.includes('rows.ghSynced') && !client.includes('rows.localOnly'))
check('create: D90 publish toggle default ON; link rides org.create-at; NO sign-in wall',
  client.includes('const [ghPublish, setGhPublish] = (0, react.useState)(true);') && client.includes('link: publishOn') && client.includes('role: "switch"') && client.includes('disabled: !ghAvailable || busy') && !client.includes('const showSignin = ghLinked === false;'))
check('disconnect: D90 keep/remove radios + typed repo gate (Remove arms only on exact slug)',
  client.includes('name: "arxa-disconnect-mode"') && client.includes('const matches = typed === target.slug;') && client.includes('disabled: phase === "busy" || (removeRepos && !matches)'))
check('disconnect: D90 org action covers project repos, project scoped; 403 relink; auto-close',
  client.includes('"org.disconnect"') && client.includes('"project.disconnect"') && client.includes('projectSlug: target.projectSlug, removeRepos }') && client.includes('errMsg.includes("re-link GitHub") && !relinking') && client.includes('setTimeout(onClose, 1100)'))
check('publish: D90 project connect rides the same modal (projectSlug scope)',
  client.includes('target.projectSlug ? "project.connect" : "github.publish"') && client.includes('"publish.projectTitle"'))
check('i18n: D90 connect/disconnect + create toggle localized (en + pl + fr)',
  client.includes('"menu.org.connect": "Connect to GitHub"') && client.includes('"menu.org.disconnect": "Disconnect GitHub…"') && client.includes('"menu.org.disconnect": "Odłącz GitHub…"') && client.includes('"menu.org.disconnect": "Déconnecter GitHub…"') && client.includes('"disconnect.typeRepo": "Type {name} to confirm removal."') && client.includes('"disconnect.typeRepo": "Wpisz {name}, aby potwierdzić usunięcie."') && client.includes('"disconnect.typeRepo": "Saisissez {name} pour confirmer la suppression."') && client.includes('"org.create.ghOffHint": "This organisation stays on this device only. Connect it later from its menu."') && client.includes('"org.create.ghOffHint": "Ta organizacja pozostaje tylko na tym urządzeniu. Połącz ją później z jej menu."') && client.includes('"org.create.ghOffHint": "Cette organisation reste uniquement sur cet appareil. Connectez-la plus tard depuis son menu."'))
check('create: D90 fragment children EVALUATE to 6 elements (guards the ASI call-chain swallow)', (() => {
  const lines = client.split('\n');
  let idx = -1;
  for (let i = 0; i < lines.length; i++) if (lines[i].includes('react_jsx_runtime.Fragment, { children: [') && lines[i + 1] && lines[i + 1].includes('org.create.location')) { idx = i; break; }
  if (idx < 0) return false;
  const region = lines.slice(idx).join('\n');
  const from = region.indexOf('children: [') + 'children: '.length;
  let depth = 0, end = -1;
  for (let pos = from; pos < region.length; pos++) { const c = region[pos]; if (c === '[') depth++; else if (c === ']') { depth--; if (depth === 0) { end = pos; break; } } }
  try {
    const el = () => ({ ok: true });
    const noop = () => {};
    const fn = new Function('react_jsx_runtime', 't', 'label', 'location', 'browseLocation', 'field', 'submit', 'folderInfo', 'publishOn', 'ghAvailable', 'busy', 'name', 'orgStore', 'onClose', 'previewPath', 'setGhPublish', 'return [' + region.slice(from + 1, end) + ']');
    const arr = fn({ jsx: el, jsxs: el, Fragment: {} }, (k) => k, {}, '', noop, {}, noop, null, true, true, false, '', { mutate: () => ({ catch: noop }) }, noop, '/root/slug', noop);
    return arr.length === 6 && arr[4] && arr[4].ok === true;
  } catch { return false; }
})())
// ---- D97: manual sync door — the org-row affordance for org.sync ----
check('sync: D97 item is org-rows-ONLY and calls ORG_POST direct (mutate discards the result)',
  client.includes('{ id: "sync", label: orgT("menu.org.sync")') &&
  client.includes('else if (id === "sync" && isOrg)') &&
  client.includes('ORG_POST("org.sync", { orgId: d.orgId })') &&
  !client.includes('orgStore.mutate("org.sync"') &&
  !client.includes('menu.project.sync'))
check('sync: D97 a failure ANYWHERE wins the badge — no green over a refused push', (() => {
  const m = client.match(/const ARXA_SYNC_BAD = (\/.*?\/);/)
  if (!m) return false
  const bad = new RegExp(m[1].slice(1, -1))
  const sweep = [{ status: "pushed" }, { slug: "project-001", status: "push-failed: OAuth App without workflow scope" }]
  return sweep.some((r) => bad.test(r.status)) && !bad.test("in-sync") && !bad.test("pushed") && !bad.test("local")
})())
check('sync: D97 badge paints the error alias and carries the raw per-repo detail',
  client.includes('"data-arxa-sync": syncState.busy ? "busy" : syncState.bad ? "failed" : "ok"') &&
  client.includes('var(--dsw-alias-state-error-primary)') &&
  !/syncState\.bad \? "var\(--dsw-alias-label-error\)"/.test(client) &&
  client.includes('title: syncState.detail || undefined'))
check('sync: D97 strings localized (en + pl + fr)',
  ["Sync with GitHub", "Synchronizuj z GitHub", "Synchroniser avec GitHub",
   "Sync failed", "Błąd synchronizacji", "Échec de la synchronisation"].every((v) => client.includes('": "' + v + '"')))


// Q5 (2026-09-03): the header chip is a CONTROL, not just a count. The
// capability map arrives from the host with every row — the browser cannot
// see the runtime that decides which verbs exist, so it must never infer them.
check('client: agent control chip renders in place of the placeholder once populated',
  ['function ArxaAgentControl(', 'function ArxaAgentRowActions(', 'ArxaAgentControl, { kind: "jobs"', 'ArxaAgentControl, { kind: "subagents"'].every((x) => client.includes(x)))
check('client: verbs are gated by the HOST capability map, never inferred in the browser',
  client.includes('row.can && row.can[verb] === true') && client.includes('row.why && row.why[verb]'))
check('client: a disabled verb still explains itself on hover',
  client.includes('t("agents.why." + String(why || "unavailable"))'))
check('client: all three verbs are offered on every row (the gap is shown, not hidden)',
  client.includes('const ARXA_AGENT_VERBS = ["pause", "resume", "cancel"]'))
check('client: actions ride the sidebar route and reload the list after one lands',
  client.includes('ORG_POST("agent.list"') && client.includes('ORG_POST("agent." + verb'))
check('client: a host refusal (ok:false) surfaces its reason instead of a silent refresh',
  client.includes('if (r && r.ok === false) setNote(t("agents.why." + String(r.reason || "unavailable")))'))
// Jobs are DISPLAYED from the client store (the push is the only live feed)
// but ACTED ON through arxa's host route — the registry is a host service and
// no `job.*` RPC exists. Both halves are pinned: a job row that starts riding
// the agent plane would 404, and a display that starts polling would fight the
// push it already gets for free.
check('client: job rows are listed from the pushed store, never fetched',
  client.includes('function arxaJobRow(') && client.includes('const rows = isJobs ? (given || []) : fetched'))
check('client: a job cancel goes to the HOST route, not the agent plane',
  client.includes('fetch("/__arxa/jobs/action"') && client.includes('action: "jobs." + verb'))
// The header slot is kind:list and ADDITIVE. arxa's chip and dsh's both render
// from state.jobsBySession once count > 0, so leaving both mounted shows TWO
// job chips — and only arxa's can act. The stock row is disabled by id in
// arxa's OWN patch (dsh's file untouched, package byte-identical), the same
// lever rows 11a/11/11c already use for ui-sidebar / ui-workspace / ui-layout.
{
  const patch = readFileSync(join(repo, 'profile/cordis.patch.yml'), 'utf8')
  check('patch: the stock ui-jobs chip is disabled, so the header shows ONE job chip',
    /- id: ui-jobs\s*\n\s*disabled: true/.test(patch))
  check('patch: arxa-jobs is still mounted to serve the route the chip calls',
    /- id: arxa-jobs\s*\n\s*name: arxa-jobs/.test(patch))
}
// Disabling the stock chip removed the only surface showing a duration, so the
// arxa row gained one. Same freeze rule as the host row: live ticks, settled
// freezes, settled-without-a-stamp shows nothing rather than a running clock.
check('client: the row shows elapsed, and a settled job with no end stamp shows none',
  client.includes('function arxaElapsed(') && client.includes('var end = live ? Date.now() : finishedAt;')
  && client.includes('if (!startedAt || !end) return "";'))
check('client: a live job\'s elapsed ticks, and the timer stops when nothing is live',
  client.includes('if (!open || !anyLive) return;') && client.includes('clearInterval(h)'))
// A whole-menu `busy` boolean greyed out BOTH rows' buttons while one was
// cancelling — the menu reporting it was busy with work it was not doing.
check('client: busy is keyed to the ONE row acting, not the whole menu',
  client.includes('const busy = busyId === row.id;') && !/ArxaAgentRowActions[^)]*busy: busy\b/.test(client))
// THE WAKE (D3). There is no content-free resume verb, so waking is a box that
// carries the human's words, not a verb button.
check('client: the wake box exists and only for a row the host marked wakeable',
  client.includes('row.can.wake === true') && client.includes('wakeRow === row.id')
  && client.includes('className: "aXa_agentWake"'))
check('client: wake sends the typed message through the sidebar route',
  client.includes('ORG_POST("agent.wake"') && client.includes('text: text'))
check('client: Enter sends the wake, Escape closes it, and an empty one never leaves the browser',
  client.includes('if (e.key === "Escape")') && client.includes('if (wakeText.trim() === "") return;'))
// Unlike a job, a subagent's state does NOT arrive by push — so this is the one
// place a reload after acting is correct.
check('client: a successful wake reloads the list (subagent state is not pushed)',
  /setWakeRow\(null\); setWakeText\(""\); setNote\(""\); load\(\);/.test(client))
for (const reason of ['subagents-only', 'message-required', 'wrong-plane']) {
  const n = (client.match(new RegExp('"agents\\.why\\.' + reason + '"\\s*:\\s*"', 'g')) ?? []).length
  check(`locale: agents.why.${reason} is defined in all 3 dictionaries (found ${n})`, n === 3)
}
check('locale: the wake control itself is translated in all 3 dictionaries',
  (client.match(/"agents\.wake"\s*:\s*"/g) ?? []).length === 3
  && (client.match(/"agents\.wakePlaceholder"\s*:\s*"/g) ?? []).length === 3)
// Only `running` arms the button. `stopping` is still live but a cancel is
// already in flight; arming it again invites a click that changes nothing.
check('client: only a RUNNING job offers cancel, and stopping says why',
  client.includes('cancel: j.status === "running"')
  && client.includes('j.status === "stopping" ? "stopping"'))
check('client: pause is refused with the job-shaped reason, not the stale no-job-api',
  client.includes('pause: "jobs-have-no-pause"') && !client.includes('cancel: "no-job-api"'))
// The registry pushes `session/jobs` on every change (measured ~154ms from
// cancel to the killed frame). Re-fetching after a job action would race that
// push and could paint an older list.
check('client: a job action does NOT reload — the push repaints it',
  /row\.kind === "job"[\s\S]{0,1200}?setNote\(""\);\s*\}, \(e\) =>/.test(client))
// Every reason the route can return must render as words, in every language.
// Count DEFINITIONS (`"key": "text"`), not mentions — `already-finished` is
// also named at its call site in act(), and counting that made this read 4.
for (const reason of ['stopping', 'not-yours', 'gone', 'registry-refused', 'already-finished', 'jobs-have-no-pause']) {
  const n = (client.match(new RegExp('"agents\\.why\\.' + reason + '"\\s*:\\s*"', 'g')) ?? []).length
  check(`locale: agents.why.${reason} is defined in all 3 dictionaries (found ${n})`, n === 3)
}
// `given` is a fresh array on every store push. Writing it into state would
// re-render, re-allocate and write again for as long as the menu sat open over
// a live job — a loop, not churn. Job rows must stay OUT of state, and `load`
// must not depend on them.
check('client: job rows never enter state, so a live job cannot spin the menu',
  client.includes('if (isJobs) return;') && /\}, \[sessionId, isJobs\]\)/.test(client)
  && !client.includes('setRows(given'))
check('client: the panel is handed the rows, since it lives in another bundle',
  client.includes('openAgentPanel(kind, sessionId, rows)') && client.includes('rows: rows || null'))
check('client: the dropdown row reveals its actions on hover (stock ToolRow behaviour)',
  client.includes('.aXa_agentActs{') && client.includes('.aXa_agentRow:hover .aXa_agentActs,.aXa_agentActs:focus-within{opacity:1}'))
check('client: the dropdown taps through to the side panel, carrying its rows',
  client.includes('aXa_agentDetails') && client.includes('openAgentPanel(kind, sessionId, rows)'))
check('client: agent verb + reason strings localized in en/pl/fr',
  ['agents.pause', 'agents.cancel', 'agents.why.no-terminate-verb', 'agents.why.no-job-api'].every((k) => (client.split('"' + k + '":').length - 1) === 3))

console.log(failures === 0 ? '\narxa-sidebar selftest: ALL GREEN' : `\narxa-sidebar selftest: ${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
