#!/usr/bin/env node
// arxa-sidebar selftest — rows-world gate (docs/plans/sidebar-org-rethink.md):
//   1. manifest shape (repo plugin convention: dsh.client.inject + lib/client.js
//      UI half, lib/index.js server half, zero runtime dependencies)
//   2. composed client headers (gen-workspace + gen-sidebar, dsh 0.1.1-rc.2)
//   3. rows-world content: org store, OrgBrowser slot, locale relabels,
//      trash surface, shell New-session org-awareness; OrgSection GONE
//   4. drift gate: regenerate (shell + workspace transform) and byte-compare
//   5. both stock dsh packages byte-identical (content hashes)
//   6. registration wired (bin/arxa-studio.mjs + profile/cordis.patch.yml:
//      stock ui-sidebar AND ui-workspace disabled — one sidebar world active)
//   7. host half: rows state/action surface + lifecycle rows faces present
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync } from 'node:fs'
import vm from 'node:vm'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..', '..')
let failures = 0
const check = (label, ok, detail = '') => {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok || !detail ? '' : ` — ${detail}`}`)
  if (!ok) failures++
}

// ---- 1. manifest shape -------------------------------------------------------
const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'))
check('manifest: name', pkg.name === 'arxa-sidebar')
check('manifest: server half', pkg.main === 'lib/index.js')
check('manifest: client half exported', pkg.exports?.['./client'] === './lib/client.js')
check('manifest: cta-state export gone', pkg.exports?.['./cta-state'] === undefined)
check('manifest: dsh.client.inject declared', Array.isArray(pkg.dsh?.client?.inject)
  && pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-layout'))
check('manifest: platform web', pkg.dsh?.client?.platform === 'web')
check('manifest: zero runtime dependencies', !pkg.dependencies)

// ---- 2. composed client headers ----------------------------------------------
const client = readFileSync(join(here, 'lib', 'client.js'), 'utf8')
// D86 gate: the bundle must PARSE. A syntax error makes the app webview load
// client.js without it ever calling __ModuleLoader__.load ("Failed to load
// plugins") while every content grep below still passes. Compile-only, no exec.
let clientParseErr = ''
try { new vm.Script(client, { filename: 'lib/client.js' }) } catch (e) { clientParseErr = String(e) }
check('client.js parses (syntax error = unloadable sidebar)', !clientParseErr, clientParseErr)
const hostSrc = () => readFileSync(join(here, 'lib', 'index.js'), 'utf8')
check('headers: workspace part names its generator',
  client.includes('GENERATED by') && client.includes('scripts/gen-workspace.mjs from @deepseek-ai/dsh-client-ui-workspace'))
check('headers: shell part names its generator',
  client.includes('scripts/gen-sidebar.mjs'))
check('headers: client.js names dsh version', client.includes('0.1.1-rc.2'))

// ---- 3. rows-world content ----------------------------------------------------
check('rows: org store present', client.includes('function createOrgStore()'))
check('rows: OrgBrowser is the slot component', client.includes('}, OrgBrowser));'))
check('rows: org data hooks pinned at the component boundary', client.includes('useWorkspaces: orgUseWorkspaces, useSessions: orgUseSessions') && client.includes('const orgUseWorkspaces = (sel) => useOrg'))
check('rows: honest content search (empty fetch)', client.includes('searchSessions: async () => ({ items: [], hasMore: false })'))
check('rows: trash surface wired (Q6)', client.includes('function TrashSection(') && client.includes('trash: () => orgStore.toggleTrash()'))
check('rows: locale relabels aboard', client.includes('"section.workspaces": "Organisations"'))
check('rows: stock Workspaces label superseded in overrides only', !client.includes('"section.workspaces": "Workspaces",\n\t\t\t\t"section.sessions"'))
check('rows: add flow opens the create-organisation modal (Q3, webview-safe)',
  client.includes('new Event("arxa-create-org")') && client.includes('function OrgCreateModal(') && client.includes('window.addEventListener("arxa-create-org", open)'))
check('create-modal: sign-in CTA carries the GitHub brand mark', client.includes('viewBox: "0 0 16 16"') && client.includes('d: GH_MARK'))
check('create-modal: sign-in step right-aligns the CTA and shows NO premature disabled submit in the footer', client.includes('justifyContent: "flex-end"') && client.includes('!showSignin && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Button, {'))
check('create-modal: device-flow code surfaces in the sign-in step (github.device poll + big code)', client.includes('"github.device"') && client.includes('github.signin.codeHint') && client.includes('devCode.userCode'))
check('create-modal: device code row has a copy button and a clickable open-link via the allowlisted host route', client.includes('"github.signin.copy"') && client.includes('"github.signin.openLink"') && client.includes('open-external') && client.includes('navigator.clipboard'))
check('rows: window.prompt is gone (Tauri WKWebView never implements it)', !client.includes('window.prompt('))
check('rows: location field opens the OS folder locator (Tauri dialog when injected, host osascript locator otherwise)',
  client.includes('window.__TAURI__.dialog') && client.includes('directory: true') && client.includes('pick-folder'))
check('host: macOS folder locator route exists', hostSrc().includes('choose folder') && hostSrc().includes('pick-folder'))
check('rows: first-run scaffolds into the picked folder or a subfolder named for the org (D77 supersedes in-place D69 — the PLATO incident)',
  client.includes('"org.create-at"') && (() => {
    const hostSrc = readFileSync(join(here, 'lib', 'index.js'), 'utf8')
    return hostSrc.includes("action === 'org.create-at'") && hostSrc.includes('shell.scaffoldOrg(target, nm)')
  })())
check('rows: org-level session creation is impossible (v2, grilled 2026-08-30) — the legacy + path is gone client AND host', !client.includes('\"org.new-session\"') && !hostSrc().includes("'org.new-session':"))
check('rows: OrgSection block deleted', !client.includes('OrgSection'))

// ---- 3b. workspace rows (org-model-v2 Phase C: D70/D71) ------------------------
check('rows-c: container rows (org/dock/project) own pseudo groups — a row survives its own collapse (v2 fix, 2026-08-30)',
  client.includes('function OrgContainerRow({ d, offset })') && client.includes('...ARXA_CONTAINER_ROWS(group.workspaceId)') && client.includes('offset: 4 + d.depth * 14 - host')
  && client.includes('...(ARXA_IS_CONTAINER_GROUP(group.workspaceId) ? [] : [(0, react_jsx_runtime.jsx)(ProjectRowItem, {')
  && client.includes('push(null, o.name)') && !client.includes('pendingRows') && !client.includes('WorkspaceRowsSection'))
check('rows-c: every container starts COLLAPSED (2026-08-30) — expansion is opt-in per row; no mount-time auto-expand',
  client.includes('if (!x[orgId]) return true;') && client.includes('const open = !!expandedMap[d.key];') && !client.includes('arxaAutoExpanded'))
check('rows-c: collapse hides descendants only — the org pseudo group never hides, leaves keep stable identity',
  client.includes('if (ws === "") return false;') && client.includes('ARXA_WS_HIDDEN(group.workspaceId)') && client.includes('emit[o.id] = [{ kind: "org"'))
check('rows-c: leaves are full stock workspace rows — indent by depth; collapse hides via display (identity never churns)',
  client.includes('ARXA_WS_INDENT(group.workspaceId)') && client.includes('ARXA_WS_HIDDEN(group.workspaceId)') && client.includes('toggleExpand(key)'))
check('rows-c: leaf click selects the workspace (composite id parse) — the ONLY startSession path',
  client.includes('ARXA_SELECT_WS(row.workspaceId)') && client.includes('workspace.new-session') && client.includes('const i = s.indexOf("|")'))
check('rows-c: real session timestamps (the 56y bug fed ordinals as ages from 1970)',
  client.includes('x.updatedAt ?? x.createdAt ?? Date.now()') && !client.includes('updatedAt: order++'))
check('rows-c: rename rides the registry — one rename, every surface',
  client.includes('"session.rename"') && client.includes('renameSession: (sessionId, title)'))
check('rows-c: leaf-row ellipsis menu hidden (fixed folders are neither renamable nor deletable)',
  client.includes('false && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Menu, {'))
check('rows-c: scope gate — orgT capture keeps stock-scope render sites locale-safe',
  client.includes('let orgT =') && client.includes('orgT = props.t')
  && /function SessionTree\(\{[^)]*\bt\b[^)]*\)\s*\{/.test(client))
check('rows-c: OrgTreeSection dissolved', !client.includes('OrgTreeSection') && !client.includes('treeRows'))
check('rows-c: selection tooltip in both locales', client.includes('"newSession.selectFirst": "Select a workspace to start a session"') && client.includes('"newSession.selectFirst": "先选择一个工作区再开始会话"'))
check('rows-c: server snapshot serves the per-org tree face + workspace-scoped sessions with real timestamps',
  hostSrc().includes('tree: treeOf(path)') && hostSrc().includes('workspace: s.workspace ?? null') && hostSrc().includes('createdAt: s.createdAt ?? null'))
check('rows-c: workspace.new-session takes a workspace path (loud on unknown); session.rename wired',
  hostSrc().includes("'workspace.new-session'") && hostSrc().includes('cur.newSession(undefined, ws)') && hostSrc().includes("'session.rename'"))

// ---- 3c. initial-snapshot gating (2025-08 create-org hang) ---------------------
// An in-place org root full of bulk content made the inline git add -A run
// for many minutes and froze the app mid-create. The contract now: create-at
// defers the snapshot (detached worker), the rows client gates the New
// Session CTA on the org's snapshotPending, and the message is human.
check('rows-snap: New Session CTA gates on the org-scoped selection + selected org snapshot state (both locales)',
  client.includes('b.disabled = !sel || snapPending')
  && client.includes('"newSession.snapshotPending": "Preparing git snapshot — sessions unlock when it lands"')
  && client.includes('"newSession.snapshotPending": "正在准备 git 快照 — 完成后即可开始会话"'))
check('rows-snap: server snapshot exposes snapshotPending (open org)', hostSrc().includes('snapshotPending: cur?.path === path'))
check('rows-snap: create-at defers the initial snapshot and honors the includeExisting choice', hostSrc().includes('deferSnapshot: true, includeExisting: arg?.includeExisting !== false'))
check('rows-snap: host answers folder-info (a count only) for the create-time question', hostSrc().includes("'arxa-sidebar-folder-info'") && hostSrc().includes('entryCount'))
check('rows-snap: modal asks the history question when the folder has content (both locales)', client.includes('"org.create.existing.title"') && client.includes('folder-info') && client.includes('includeExisting: snapChoice') && client.includes('"org.create.existing.only": "arxa\'s files only (recommended) — your existing files stay untouched and untracked"') && client.includes('"org.create.existing.only": "仅 arxa 文件（推荐）— 现有文件保持原样、不被跟踪"'))
check('rows-snap: create submit refreshes through the store (gate lifts at once, no create-again loop)', client.includes('orgStore.mutate("org.create-at"') && !client.includes('ORG_POST("org.create-at"'))
check('welcome: blank-page gate with card when no org (D69 UX)', client.includes('function WelcomeGate(') && client.includes('"welcome.title": "Welcome to arxa studio"') && client.includes('"welcome.title": "欢迎使用 arxa studio"') && client.includes('!creating && (0, react_jsx_runtime.jsx)(WelcomeGate'))
check('welcome: TWO buttons - arxa studio (create) + arxa business (disabled, later)', client.includes('t("welcome.studio")') && client.includes('t("welcome.business")') && client.includes('"welcome.businessSoon"') && !client.includes('t("welcome.cta")'))
check('welcome: one-shot resume to newest session of the open org', client.includes('resumeTried') && client.includes('maybeResume(next.orgs)') && client.includes('orgStore.mutate("session.open"'))
check('content area (2026-08-30): arxa is the sole driver — row open + resume focus the conversation via the client sessions service (dsh own open call)',
  client.includes('arxaOpenConversation(sessionId)') && client.includes('arxaOpenConversation(cand.id)') && client.includes('arxaClientSessions.open(dshId)') && client.includes('snap.ids.includes(dshId)'))
check('content area: a boot with nothing to resume clears the selection — stranding pre-arxa/hero sessions stop riding along',
  client.includes('arxaClientSessions.clear()') && client.includes('clearIfNothingToResume') && client.includes('let bootDecided = false;'))
check('content area: the boot clear SURVIVES dsh startup reconnect (workspaces.startInitialSelection re-opens the recent workspace blank session over an early clear) — bounded re-assert, org/user opens win',
  client.includes('reassertEmpty') && client.includes('workspaces.startInitialSelection') && client.includes('if (orgIds.has(cur)) return;') && client.includes('if (tries > 20) return;'))
check('content area (live, once-and-for-all): the rider kill is condition-driven, not a stopwatch — any current session that is not an OPEN org one is cleared on every store bump while no user/resume open owns the content (slow-boot stranding loses every race)',
  client.includes('enforceNoRiders') && client.includes('x.state === "open"') && client.includes('orgStore.refresh().then(enforceNoRiders)'))
check('content area (live): cross-client archive/rename reach every client without waiting on the 5s poll — the org view refreshes on dsh store bumps (sig-gated refresh makes repeats a no-op)',
  client.includes('ctx.get("workspaces").list.subscribe') && client.includes('arxaClientSessions.list.subscribe') && client.includes('orgStore.refresh()'))
check('content area: the hero workspace picker is replaced by arxa guidance (raw engine sessions cannot be born from the hero)',
  client.includes('ArxaHeroGuide') && client.includes('"conversation.hero.workspace"') && client.includes('"hero.guide": "Sessions start inside a workspace') && client.includes('"hero.guide": "会话从工作区开始'))
check('content area: with NOTHING bound the text composer is hidden outright (2026-08-30 user ask) — a bound blank session keeps its composer',
  client.includes('[data-arxa-empty] [data-slot=') && client.includes('data-arxa-empty') && client.includes('const unbound = !snap || snap.current === void 0 || snap.current === null;'))
check('empty state (2026-08-30 polish): guidance centered and spaced, arxa glyph in the hero lockup (brand plugin paints the mark, sidebar centers its slot)',
  client.includes('[data-arxa-empty] [data-arxa-hero-guide]{text-align:center') && client.includes('margin:12px auto 0') && !client.includes('textAlign: "left"'));

// ---- 4. drift gate ------------------------------------------------------------
// The committed client.js must equal shell+workspace regenerated, byte for
// byte. A hand-edit to client.js (or a stale snippet) goes RED here — fix the
// source (script/snippets), never the generated file. rc-bump policy lives in
// scripts/gen-workspace.mjs.
{
  const rootDir = join(here, '..', '..')
  const r = spawnSync(process.execPath, [join(rootDir, 'scripts', 'gen-workspace.mjs')], {
    cwd: rootDir, encoding: 'utf8', timeout: 60_000,
  })
  const regen = r.stdout ?? ''
  check('drift gate: client.js equals both transforms regenerated',
    r.status === 0 && regen === client,
    r.status === 0 ? 'byte drift — regenerate, or fix scripts/gen-*.mjs / snippets' : String(r.stderr).slice(0, 200))
}

// ---- 5. original dsh packages byte-identical ----------------------------------
// Parent-walk resolution: works from the main checkout AND from a git
// worktree nested under it (no node_modules of its own).
const hashPkg = (specifier, expected) => {
  const pkgDir = dirname(createRequire(import.meta.url).resolve(specifier + '/package.json'))
  const files = []
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const f = join(d, e.name)
      e.isDirectory() ? walk(f) : files.push(f)
    }
  }
  walk(pkgDir)
  const hash = createHash('sha256')
  for (const f of files) {
    hash.update(relative(pkgDir, f))
    hash.update('\0')
    hash.update(readFileSync(f))
    hash.update('\0')
  }
  const got = hash.digest('hex')
  return { got, ok: got === expected }
}
{
  const s = hashPkg('@deepseek-ai/dsh-client-ui-sidebar',
    '04d3a1afb6793bd9de0a26eb82b1266ecdf78da03899c5c32ac4258bf242c4e7')
  check('reference: dsh sidebar package byte-identical', s.ok, 'expected 04d3a1af…')
  const w = hashPkg('@deepseek-ai/dsh-client-ui-workspace',
    'db871ccc02577da5a5fe31420456b78ca390d40d2cc0a75322a120d218e810e3')
  check('reference: dsh workspace package byte-identical', w.ok, 'expected db871ccc…')
}

// ---- 6. registration wired ---------------------------------------------------
const bin = readFileSync(join(repo, 'bin', 'arxa-studio.mjs'), 'utf8')
check('registration: profile dependency', bin.includes("'arxa-sidebar': `file:${sidebarDir}`"))
check('registration: BY_NAME_PLUGINS', /BY_NAME_PLUGINS = \[[^\]]*'arxa-sidebar'/.test(bin))
check('registration: packed-mode copy list', bin.includes("['arxa-sidebar', sidebarDir]"))
const patch = readFileSync(join(repo, 'profile', 'cordis.patch.yml'), 'utf8')
check('registration: arxa-sidebar inserted', /id: arxa-sidebar\s*\n\s*name: arxa-sidebar/.test(patch))
check('registration: stock ui-sidebar disabled', /- id: ui-sidebar\s*\n\s*disabled: true/.test(patch))
check('registration: stock ui-workspace disabled (rows world owns the section)',
  /- id: ui-workspace\s*\n\s*disabled: true/.test(patch))

// ---- 7. host half + lifecycle rows faces --------------------------------------
const host = await import('./lib/index.js')
check('host: SEAM_LIFECYCLE_STUBBED declared', typeof host.SEAM_LIFECYCLE_STUBBED === 'boolean')
check('host: cta-state module gone', !readFileSync(join(here, 'lib', 'index.js'), 'utf8').includes('cta-state'))
let mod = null
try { mod = await import('arxa-file-org-shell') } catch {}
if (!mod) {
  try { mod = await import(new URL('../file-org-shell/lib/index.js', import.meta.url).href) } catch {}
}
check('seam: arxa-file-org-shell resolves with createOrgLifecycle', typeof mod?.createOrgLifecycle === 'function')
{
  // renameOrg is a verb ON an instance — build one against a throwaway root.
  const { mkdtempSync } = await import('node:fs')
  const os = await import('node:os')
  const svc = mod.createOrgLifecycle({ workspaceRoot: mkdtempSync(join(os.tmpdir(), 'arxa-rows-')), env: { ARXA_HOME: os.tmpdir() } })
  check('rows face: lifecycle exposes renameOrg (D41 manifest-only)', typeof svc.renameOrg === 'function')
}
{
  // The 2025-08 create-org hang, end-to-end against the REAL lifecycle on a
  // throwaway root: a deferred open leaves the snapshot pending (CTA-gated),
  // session creation refuses with a human reason, and the detached worker
  // lands HEAD on its own — the gate lifts itself without any caller waiting.
  const { mkdtempSync, mkdirSync, rmSync, writeFileSync } = await import('node:fs')
  const os = await import('node:os')
  const root = mkdtempSync(join(os.tmpdir(), 'arxa-snap-'))
  try {
    const orgPath = join(root, 'bulk-org')
    mkdirSync(orgPath, { recursive: true }) // D69: scaffold IN PLACE — the folder exists first
    // Real bulk: an empty fixture let the detached snapshot land before the
    // probe raced it (seen live 2026-08-30) — give the worker actual work so
    // \"pending\" holds long enough to observe.
    for (let i = 0; i < 400; i++) writeFileSync(join(orgPath, 'bulk-' + i + '.md'), 'bulk content\n')
    mod.scaffoldOrg(orgPath, 'Snap Org')
    // env is NOT optional here: openOrg → touchRecent inherits process.env
    // by default and would front-load this throwaway root into the REAL
    // ~/.arxa/organisation.json on every npm test run (seen live 2025-08:
    // eight dead arxa-snap-* entries squatting the user's recents).
    const l2 = mod.createOrgLifecycle({ workspaceRoot: root, env: { ARXA_HOME: root } })
    await l2.openOrg(orgPath, { deferSnapshot: true })
    check('rows-snap: deferred open reports snapshotPending true', l2.current.snapshotPending() === true)
    let guardMsg = ''
    try { await l2.current.newSession('probe', 'notes') } catch (e) { guardMsg = String(e?.message ?? e) }
    check('rows-snap: session creation refuses with a human reason while pending', guardMsg.includes('initial-snapshot-pending'))
    const deadline = Date.now() + 20000
    while (l2.current.snapshotPending() && Date.now() < deadline) await new Promise((r) => setTimeout(r, 100))
    check('rows-snap: detached snapshot lands HEAD; gate lifts itself', l2.current.snapshotPending() === false)
    try { l2.closeOrg() } catch {}
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}
check('rows face: host-served read-only exports (listSessions/listTrash)', typeof mod?.listSessions === 'function' && typeof mod?.listTrash === 'function')
check('rows face: workspace-root discovery exported', typeof mod?.loadWorkspaceRoot === 'function')

// ---- 8. pendingInteraction producer-consumer wiring (D63) ----------------------
// The producer is dsh itself: client-runtime SessionManager classifies
// question/requested mux frames into SessionSummary.pendingInteraction
// (approval | plan-review | question — 0.1.1-rc.2). The sidebar consumes it
// in three places; regeneration dropping any one silently strands the union
// (rows would never show the waiting pills), so pin all three.
check('wiring: session rows spread pendingInteraction',
  client.includes('...s.pendingInteraction === void 0 ? {} : { pendingInteraction: s.pendingInteraction }'))
check('wiring: search rows spread pendingInteraction',
  client.includes('...summary.pendingInteraction === void 0 ? {} : { pendingInteraction: summary.pendingInteraction }'))
check('wiring: status switch covers the closed union',
  client.includes('case "approval":') && client.includes('case "plan-review":')
  && client.includes('case "question":') && client.includes('assertNever(node.pendingInteraction)'))
check('wiring: runtime producer present (SessionManager pendingInteractions)',
  (() => {
    try {
      const rt = readFileSync(join(repo, 'node_modules', '@deepseek-ai', 'dsh-client-runtime', 'lib', 'client.js'), 'utf8')
      return rt.includes('pendingInteractions') && rt.includes('questionInteractionStatus')
    } catch { return false }
  })())

// ---- 9. D73/D74 github publish wiring ------------------------------------------
// The silent drop: getLifecycle built the lifecycle WITHOUT github faces, so
// the throw-proof stub answered github-unavailable for every publish while
// the account was linked (measured 2026-08-30 on TOPO project-001). Pin the
// exact injection expression, the manual-publish action, and the menu row.
check('github: the lifecycle is created WITH github faces injected (D73 root-cause fix)',
  hostSrc().includes('github: github ?? undefined'))
check('github: import failure degrades to the loud stub, never a crash',
  hostSrc().includes('await getGithub().catch(() => undefined)'))
check('github: manual publish action routes to the open-org handle (D74 hybrid heal)',
  hostSrc().includes("'github.publish'") && hostSrc().includes('cur.publishGithub()'))
check('github: org menu carries the Publish row (en + zh)',
  client.includes('"github.publish"') && client.includes('menu.org.publish'))
check('github: publish label localized',
  client.includes('"menu.org.publish": "Publish to GitHub"') && client.includes('"menu.org.publish": "发布到 GitHub"'))

// ---- D77 (the PLATO incident): publish silence + placement trap ----
// The menu's publish row used to fire-and-forget (mutate().catch(() => {})):
// a refused publish (no HEAD, not linked) looked like NOTHING happened, and
// the create modal's location semantics made a volume ROOT the org (git init
// over the whole disk). Pin the redirect and the modal phase machine.
check('create-at: org scaffolds into picked/<org-name> unless the folder already carries the name (D77)',
  hostSrc().includes('const target = pickedSlug === nameSlug ? expanded : path.join(expanded, nameSlug)'))
check('create-at: the redirect reuses the real slugify (no drift from D41 slugs)',
  hostSrc().includes("import(new URL('../../workspace/lib/slug.js', import.meta.url).href)"))
check('create-at: an org name with no slug fails loud before any disk write',
  hostSrc().includes("'org name has no slug: '"))
check('publish: the menu row dispatches the modal event (no swallowed mutate)',
  client.includes('"arxa-publish-org"') && !client.includes('orgStore.mutate("github.publish"'))
check('publish: modal runs the phase machine over the publish result',
  client.includes('function OrgPublishModal') && client.includes('ORG_POST("github.publish"') && client.includes('initial-snapshot-pending'))
check('publish: modal localized (en + zh)',
  client.includes('"publish.confirmCta": "Publish"') && client.includes('"publish.confirmCta": "发布"'))

// ---- D79: GitHub-parity labels + named project creation (D78 riders) ----
// v3 containers carry their stage prefix on GitHub ("00-moodboard"); the
// tree shows the SAME real directory name. Only a genuine dictionary hit
// (a pre-v3 folder like "moodboard") prettifies — no stem mapping, no
// TitleCase, and never a leaked raw tree.pc key.
check('labels: stage containers render their real directory name (GitHub parity)',
  client.includes('const hit = orgT("tree.pc." + c);') &&
  client.includes('if (hit && hit !== "tree.pc." + c) return hit;') &&
  client.includes('return c;') &&
  !client.includes('stemHit') && !client.includes('const stem ='))
check('project create: the dock + opens a NAME modal (no pregenerated names in the UI)',
  client.includes('"arxa-create-project"') && client.includes('function OrgProjectModal') && !client.includes('orgStore.mutate("project.create"'))
check('project create: modal sends the typed name through project.create',
  client.includes('ORG_POST("project.create", { orgId: target.orgId, name: n })'))
check('project create: modal localized (en + zh)',
  client.includes('"project.create": "Create project"') && client.includes('"project.create": "创建项目"'))

// ---- D80: row menus, the rename ride, the Trash row ----
check('menus: ONLY org + project rows carry the kebab (docks/containers never)',
  client.includes('const showMenu = isOrg || d.kind === "project";') && client.includes('showMenu && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Menu, {') && !client.includes('isOrg && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Menu'))
check('menus: org Rename + project Rename/Trash items',
  client.includes('"menu.org.rename"') && client.includes('"menu.project.rename"') && client.includes('"menu.project.trash"') && !client.includes('id: "trash", label: orgT("menu.trash")'))
check('rename: the modal drives org.rename and project.rename',
  client.includes('function OrgRenameModal') && client.includes('ORG_POST("org.rename"') && client.includes('ORG_POST("project.rename"'))
check('rename: events wired both directions',
  client.includes('"arxa-rename-org"') && client.includes('"arxa-rename-project"') && client.includes('window.addEventListener("arxa-rename-org", onRenameOrg)') && client.includes('window.addEventListener("arxa-rename-project", onRenameProject)'))
check('trash: a permanent divider row with count badge + empty state (en + zh)',
  client.includes('function TrashSection') && client.includes('borderTop: "1px solid var(--dsw-alias-border-l2') && client.includes('"trash.empty": "Trash is empty"') && client.includes('"trash.empty": "废纸篓是空的"') && !client.includes('if (rows.length === 0 || !view.open) return null;'))
check('routes: project.rename drives the full-move machinery; project.trash parks locally',
  hostSrc().includes("'project.rename'") && hostSrc().includes('l.renameProject(cur.path, arg.projectSlug, arg.name)') && hostSrc().includes("'project.trash'") && hostSrc().includes('cur.trashProject(arg.projectSlug)'))

// ---- D81: the org itself is trashable; Delete forever really deletes ----
check('purge: the modal drives orgtrash.purge and projecttrash.purge',
  client.includes('function OrgPurgeModal') && client.includes('"orgtrash.purge" : "projecttrash.purge"'))
check('purge: the trash row dispatches the confirmation event',
  client.includes('"arxa-purge-trash"') && client.includes('window.addEventListener("arxa-purge-trash", onPurge)'))
check('trash: org group + delete-forever + project group (localized en + zh)',
  client.includes('"trash.orgSection": "Organisations"') && client.includes('"trash.orgSection": "组织"') && client.includes('"trash.projectSection": "Projects"') && client.includes('"trash.projectSection": "项目"') && client.includes('"trash.deleteForever": "Delete forever"') && client.includes('"trash.deleteForever": "永久删除"'))
check('routes: org trash/restore/purge wired to the service faces',
  hostSrc().includes("'org.trash'") && hostSrc().includes('l.trashOrg(orgByRef(arg?.orgId).path)') && hostSrc().includes("'orgtrash.restore'") && hostSrc().includes('l.restoreOrg(arg?.entryId)') && hostSrc().includes('l.purgeOrgTrash(arg.entryId)') && hostSrc().includes('cur.purgeTrash(arg.entryId)'))

// ---- D82: org-menu Move to Trash + design-system trash surface ----
check('menus: org menu REGAINS Move to Trash (danger) dispatching org.trash',
  client.includes('id: "trash", label: orgT("menu.org.trash")') && client.includes('orgStore.mutate("org.trash", { orgId: d.orgId })') && client.includes('"menu.org.trash": "Move to Trash"') && client.includes('"menu.org.trash": "移到废纸篓"'))
check('menus: every row-menu item carries a design-system glyph (edit/folder/github/trash)',
  client.includes('IconEditOutline16') && client.includes('icon: ghMark16') && client.includes('IconTrashOutline16, {}), danger: true }'))
check('menus: D87 close is GONE (unscoped verb — opening another org already switches)',
  !client.includes('id: "close"') && !client.includes('menu.org.close') && !client.includes('IconCloseOutline16'))
check('trash: header rides the tree-row chevron (arrow/arrowOpen) — no text glyph',
  client.includes('IconTriangleRightFill14, { className: clsx(Rows_module_css_default.arrow, open && Rows_module_css_default.arrowOpen) })') && !client.includes('children: "▶"'))
check('trash: entries use rowActions icon buttons under Tooltips (restore=refresh, delete=trash in critical ink)',
  client.includes('.Tooltip, {') && client.includes('IconRefreshOutline16, onRestore') && client.includes('IconTrashOutline16, onPurge, true') && client.includes('className: Rows_module_css_default.iconButton'))
check('trash: auto-opens while anything is trashed; manual toggle wins',
  client.includes('const [manual, setManual] = (0, react.useState)(null);') && client.includes('const open = manual === null ? total > 0 : manual;'))
check('trash: org glyph shared between tree row and trash org entries (single def)',
  client.includes('function OrgGlyph({ size })') && client.split('function OrgGlyph({ size })').length === 2 && client.includes('entryRow(e, (0, react_jsx_runtime.jsx)(OrgGlyph, {}), () => restoreOrg'))
// ---- D83: trash lives under the last org row; icons keep their spacing ----
check('trash: rides the grouped tree tail via ARXA_TRASH_AFTER_ORGS (no bottom mount)',
  client.includes('const ARXA_TRASH_AFTER_ORGS = () => orgT ? (0, react_jsx_runtime.jsx)(TrashSection, { t: orgT, key: "arxa-trash" }) : null;') && client.includes('}), ARXA_TRASH_AFTER_ORGS()]') && !client.includes('TrashSection, { t: props.t }'))
check('trash: restore/delete icon buttons are gapped (flex span, 4px)',
  client.includes('style: { display: "flex", gap: 4, flex: "none", alignItems: "center" }, children: [') && client.includes('IconRefreshOutline16, onRestore),') && client.includes('IconTrashOutline16, onPurge, true)'))
// ---- D84: the trash reads exactly like the tree above it ----
check('trash: header row IS an org row (projectRow class, treeitem, 600 weight, no kebab)',
  client.includes('style: { marginLeft: 4, marginTop: 4, borderRadius: 6, cursor: "pointer", fontWeight: 600 }') && client.includes('"aria-expanded": open,') && client.includes('className: Rows_module_css_default.title, children: t("trash.section")') && !client.includes('borderRadius: 8, padding: "0 6px"'))
check('trash: header count is the plain org-row count (11px, no pill)',
  client.split('fontSize: 11, opacity: 0.55, flex: "none", marginRight: 4').length === 3)
check('trash: entries are stock project rows at the depth-1 margin (18px, 14px title class)',
  client.includes('style: { marginLeft: 18, marginTop: 2, cursor: "default" }') && client.includes('className: Rows_module_css_default.projectText, children: (0, react_jsx_runtime.jsx)("span", { className: Rows_module_css_default.title, title: e.entryId'))
check('trash: group labels are glyph-free 10px captions (no uppercase TRASHED wording anywhere)',
  client.includes('fontSize: 10, lineHeight: "16px", letterSpacing: "0.06em"') && client.includes('groupLabel(t("trash.orgSection"))') && !client.includes('groupLabel((0, react_jsx_runtime.jsx)(') && !client.includes('Trashed'))
// ---- D85: the 403 delete_repo dead-end upgrades itself ----
check('purge: the scope-stale 403 offers re-link & retry in the modal (device flow inline)',
  client.includes('errMsg.includes("re-link GitHub") && !relinking') && client.includes('onClick: relink') && client.includes('const relink = () => {') && client.includes('ORG_POST("github.link").then(() => {'))
check('purge: the re-link surfaces the one-time code and AUTO-retries the same purge',
  client.includes('ORG_POST("github.device").then((r) => {') && client.includes('if (d && d.userCode) setDevCode(d);') && client.includes('children: devCode.userCode') && client.includes('setRelinking(false); setDevCode(null);\n\t\t\t\t\tsubmit();'))
check('purge: re-link strings localized (en + zh)',
  client.includes('"purge.relink": "Re-link GitHub & retry"') && client.includes('"purge.relink": "重新关联 GitHub 并重试"') && client.includes('"purge.relinkHint"'))
// ---- D88: ghost-row sync fix + GitHub-style typed delete gate ----
check('store: orgTrash rides the change signature (purge-only mutations must land)',
  client.includes('next.orgTrash, next.trashCount'))
check('purge: D88 typed-name gate arms Delete forever (exact, case-sensitive row label)',
  client.includes('const matches = typed === target.name;') && client.includes('disabled: !matches || phase === "busy"') && client.includes('t("purge.typeName").replace("{name}", target.name)') && client.includes('placeholder: target.name'))
check('purge: D88 busy LOCK (Close dead while deleting) + retry + auto-close + summary',
  client.includes('variant: "outline", disabled: phase === "busy", onClick: dismiss') && client.includes('t("purge.retry")') && client.includes('setTimeout(onClose, 1100)') && client.includes('res.deletedRepos.join(", ")'))
check('purge: D88 typed gate + retry localized (en + zh)',
  client.includes('"purge.typeName": "Type {name} exactly to confirm."') && client.includes('"purge.typeName": "输入 {name} 以确认。"') && client.includes('"purge.retry": "Try again"') && client.includes('"purge.retry": "重试"'))
console.log(failures === 0 ? '\narxa-sidebar selftest: ALL GREEN' : `\narxa-sidebar selftest: ${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
