#!/usr/bin/env node
// arxa-sidebar selftest — rows-world gate (docs/plans/sidebar-org-rethink.md):
//   1. manifest shape (repo plugin convention: dsh.client.inject + lib/client.js
//      UI half, lib/index.js server half, zero runtime dependencies)
//   2. composed client headers (gen-workspace + gen-sidebar, dsh 0.1.1-rc.2)
//   3. rows-world content: org store, OrgBrowser slot, locale relabels,
//      trash surface, shell New-session org-awareness; OrgSection GONE
//   4. drift gate: regenerate (shell + workspace transform) and byte-compare
//   5. both stock dsh packages byte-identical (content hashes)
//   6. registration wired (bin/arxa-studio.mjs + profile/cordis.patch.yml:
//      stock ui-sidebar AND ui-workspace disabled — one sidebar world active)
//   7. host half: rows state/action surface + lifecycle rows faces present
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..', '..')
let failures = 0
const check = (label, ok, detail = '') => {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok || !detail ? '' : ` — ${detail}`}`)
  if (!ok) failures++
}

// ---- 1. manifest shape -------------------------------------------------------
const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'))
check('manifest: name', pkg.name === 'arxa-sidebar')
check('manifest: server half', pkg.main === 'lib/index.js')
check('manifest: client half exported', pkg.exports?.['./client'] === './lib/client.js')
check('manifest: cta-state export gone', pkg.exports?.['./cta-state'] === undefined)
check('manifest: dsh.client.inject declared', Array.isArray(pkg.dsh?.client?.inject)
  && pkg.dsh.client.inject.includes('@deepseek-ai/dsh-client-ui-layout'))
check('manifest: platform web', pkg.dsh?.client?.platform === 'web')
check('manifest: zero runtime dependencies', !pkg.dependencies)

// ---- 2. composed client headers ----------------------------------------------
const client = readFileSync(join(here, 'lib', 'client.js'), 'utf8')
const hostSrc = () => readFileSync(join(here, 'lib', 'index.js'), 'utf8')
check('headers: workspace part names its generator',
  client.includes('GENERATED by') && client.includes('scripts/gen-workspace.mjs from @deepseek-ai/dsh-client-ui-workspace'))
check('headers: shell part names its generator',
  client.includes('scripts/gen-sidebar.mjs'))
check('headers: client.js names dsh version', client.includes('0.1.1-rc.2'))

// ---- 3. rows-world content ----------------------------------------------------
check('rows: org store present', client.includes('function createOrgStore()'))
check('rows: OrgBrowser is the slot component', client.includes('}, OrgBrowser));'))
check('rows: org data hooks pinned at the component boundary', client.includes('useWorkspaces: orgUseWorkspaces, useSessions: orgUseSessions') && client.includes('const orgUseWorkspaces = (sel) => useOrg'))
check('rows: honest content search (empty fetch)', client.includes('searchSessions: async () => ({ items: [], hasMore: false })'))
check('rows: trash surface wired (Q6)', client.includes('function TrashSection(') && client.includes('trash: () => orgStore.toggleTrash()'))
check('rows: locale relabels aboard', client.includes('"section.workspaces": "Organisations"'))
check('rows: stock Workspaces label superseded in overrides only', !client.includes('"section.workspaces": "Workspaces",\n\t\t\t\t"section.sessions"'))
check('rows: add flow opens the create-organisation modal (Q3, webview-safe)',
  client.includes('new Event("arxa-create-org")') && client.includes('function OrgCreateModal(') && client.includes('window.addEventListener("arxa-create-org", open)'))
check('create-modal: sign-in CTA carries the GitHub brand mark', client.includes('viewBox: "0 0 16 16"') && client.includes('d: GH_MARK'))
check('create-modal: sign-in step right-aligns the CTA and shows NO premature disabled submit in the footer', client.includes('justifyContent: "flex-end"') && client.includes('!showSignin && (0, react_jsx_runtime.jsx)(_deepseek_ai_dsh_client_ui_primitives.Button, {'))
check('create-modal: device-flow code surfaces in the sign-in step (github.device poll + big code)', client.includes('"github.device"') && client.includes('github.signin.codeHint') && client.includes('devCode.userCode'))
check('create-modal: device code row has a copy button and a clickable open-link via the allowlisted host route', client.includes('"github.signin.copy"') && client.includes('"github.signin.openLink"') && client.includes('open-external') && client.includes('navigator.clipboard'))
check('rows: window.prompt is gone (Tauri WKWebView never implements it)', !client.includes('window.prompt('))
check('rows: location field opens the OS folder locator (Tauri dialog when injected, host osascript locator otherwise)',
  client.includes('window.__TAURI__.dialog') && client.includes('directory: true') && client.includes('pick-folder'))
check('host: macOS folder locator route exists', hostSrc().includes('choose folder') && hostSrc().includes('pick-folder'))
check('rows: first-run creates the org IN the picked folder (D69 supersedes D36)',
  client.includes('"org.create-at"') && (() => {
    const hostSrc = readFileSync(join(here, 'lib', 'index.js'), 'utf8')
    return hostSrc.includes("action === 'org.create-at'") && hostSrc.includes('shell.scaffoldOrg(expanded, nm)')
  })())
check('rows: shell New-session is org-aware (Q5)', client.includes('org.new-session') && client.includes('Open an organisation first'))
check('rows: OrgSection block deleted', !client.includes('OrgSection'))

// ---- 3b. workspace rows (org-model-v2 Phase C: D70/D71) ------------------------
check('rows-c: WorkspaceRowsSection aboard (the rows ARE the tree)', client.includes('function WorkspaceRowsSection('))
check('rows-c: OrgTreeSection dissolved', !client.includes('OrgTreeSection') && !client.includes('treeRows'))
check('rows-c: selection face + gated startSession splice', client.includes('selectRow(rowId)') && client.includes('workspace.new-session') && client.includes('const sel = orgStore.get().selectedRowId;'))
check('rows-c: selection hint + section label in both locales', client.includes('"rows.section": "Workspaces"') && client.includes('"newSession.selectFirst": "Select a workspace to start a session"') && client.includes('"rows.section": "工作区"'))
check('rows-c: server snapshot serves rows (category + project rowIds)', hostSrc().includes("rowId: 'category:'") && hostSrc().includes("rowId: 'project:'"))
check('rows-c: server act maps rowId → scoped session', hostSrc().includes("'workspace.new-session'") && hostSrc().includes('cur.newSession(undefined, proj)'))

// ---- 3c. initial-snapshot gating (2025-08 create-org hang) ---------------------
// An in-place org root full of bulk content made the inline git add -A run
// for many minutes and froze the app mid-create. The contract now: create-at
// defers the snapshot (detached worker), the rows client gates the New
// Session CTA on the org's snapshotPending, and the message is human.
check('rows-snap: New Session CTA gates on the org snapshot state (both locales)',
  client.includes('b.disabled = !selectedRowId || snapPending')
  && client.includes('"newSession.snapshotPending": "Preparing git snapshot — sessions unlock when it lands"')
  && client.includes('"newSession.snapshotPending": "正在准备 git 快照 — 完成后即可开始会话"'))
check('rows-snap: server snapshot exposes snapshotPending (open org)', hostSrc().includes('snapshotPending: cur?.path === path'))
check('rows-snap: create-at defers the initial snapshot (request never waits on bulk content)', hostSrc().includes('openOrg(created.path, { deferSnapshot: true })'))
check('welcome: blank-page gate with card when no org (D69 UX)', client.includes('function WelcomeGate(') && client.includes('"welcome.title": "Welcome to arxa studio"') && client.includes('"welcome.title": "欢迎使用 arxa studio"') && client.includes('!creating && (0, react_jsx_runtime.jsx)(WelcomeGate'))
check('welcome: TWO buttons - arxa studio (create) + arxa business (disabled, later)', client.includes('t("welcome.studio")') && client.includes('t("welcome.business")') && client.includes('"welcome.businessSoon"') && !client.includes('t("welcome.cta")'))
check('welcome: one-shot resume to newest session of the open org', client.includes('resumeTried') && client.includes('maybeResume(next.orgs)') && client.includes('action: "session.open"'))

// ---- 4. drift gate ------------------------------------------------------------
// The committed client.js must equal shell+workspace regenerated, byte for
// byte. A hand-edit to client.js (or a stale snippet) goes RED here — fix the
// source (script/snippets), never the generated file. rc-bump policy lives in
// scripts/gen-workspace.mjs.
{
  const rootDir = join(here, '..', '..')
  const r = spawnSync(process.execPath, [join(rootDir, 'scripts', 'gen-workspace.mjs')], {
    cwd: rootDir, encoding: 'utf8', timeout: 60_000,
  })
  const regen = r.stdout ?? ''
  check('drift gate: client.js equals both transforms regenerated',
    r.status === 0 && regen === client,
    r.status === 0 ? 'byte drift — regenerate, or fix scripts/gen-*.mjs / snippets' : String(r.stderr).slice(0, 200))
}

// ---- 5. original dsh packages byte-identical ----------------------------------
// Parent-walk resolution: works from the main checkout AND from a git
// worktree nested under it (no node_modules of its own).
const hashPkg = (specifier, expected) => {
  const pkgDir = dirname(createRequire(import.meta.url).resolve(specifier + '/package.json'))
  const files = []
  const walk = (d) => {
    for (const e of readdirSync(d, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const f = join(d, e.name)
      e.isDirectory() ? walk(f) : files.push(f)
    }
  }
  walk(pkgDir)
  const hash = createHash('sha256')
  for (const f of files) {
    hash.update(relative(pkgDir, f))
    hash.update('\0')
    hash.update(readFileSync(f))
    hash.update('\0')
  }
  const got = hash.digest('hex')
  return { got, ok: got === expected }
}
{
  const s = hashPkg('@deepseek-ai/dsh-client-ui-sidebar',
    '04d3a1afb6793bd9de0a26eb82b1266ecdf78da03899c5c32ac4258bf242c4e7')
  check('reference: dsh sidebar package byte-identical', s.ok, 'expected 04d3a1af…')
  const w = hashPkg('@deepseek-ai/dsh-client-ui-workspace',
    'db871ccc02577da5a5fe31420456b78ca390d40d2cc0a75322a120d218e810e3')
  check('reference: dsh workspace package byte-identical', w.ok, 'expected db871ccc…')
}

// ---- 6. registration wired ---------------------------------------------------
const bin = readFileSync(join(repo, 'bin', 'arxa-studio.mjs'), 'utf8')
check('registration: profile dependency', bin.includes("'arxa-sidebar': `file:${sidebarDir}`"))
check('registration: BY_NAME_PLUGINS', /BY_NAME_PLUGINS = \[[^\]]*'arxa-sidebar'/.test(bin))
check('registration: packed-mode copy list', bin.includes("['arxa-sidebar', sidebarDir]"))
const patch = readFileSync(join(repo, 'profile', 'cordis.patch.yml'), 'utf8')
check('registration: arxa-sidebar inserted', /id: arxa-sidebar\s*\n\s*name: arxa-sidebar/.test(patch))
check('registration: stock ui-sidebar disabled', /- id: ui-sidebar\s*\n\s*disabled: true/.test(patch))
check('registration: stock ui-workspace disabled (rows world owns the section)',
  /- id: ui-workspace\s*\n\s*disabled: true/.test(patch))

// ---- 7. host half + lifecycle rows faces --------------------------------------
const host = await import('./lib/index.js')
check('host: SEAM_LIFECYCLE_STUBBED declared', typeof host.SEAM_LIFECYCLE_STUBBED === 'boolean')
check('host: cta-state module gone', !readFileSync(join(here, 'lib', 'index.js'), 'utf8').includes('cta-state'))
let mod = null
try { mod = await import('arxa-file-org-shell') } catch {}
if (!mod) {
  try { mod = await import(new URL('../file-org-shell/lib/index.js', import.meta.url).href) } catch {}
}
check('seam: arxa-file-org-shell resolves with createOrgLifecycle', typeof mod?.createOrgLifecycle === 'function')
{
  // renameOrg is a verb ON an instance — build one against a throwaway root.
  const { mkdtempSync } = await import('node:fs')
  const os = await import('node:os')
  const svc = mod.createOrgLifecycle({ workspaceRoot: mkdtempSync(join(os.tmpdir(), 'arxa-rows-')) })
  check('rows face: lifecycle exposes renameOrg (D41 manifest-only)', typeof svc.renameOrg === 'function')
}
{
  // The 2025-08 create-org hang, end-to-end against the REAL lifecycle on a
  // throwaway root: a deferred open leaves the snapshot pending (CTA-gated),
  // session creation refuses with a human reason, and the detached worker
  // lands HEAD on its own — the gate lifts itself without any caller waiting.
  const { mkdtempSync, mkdirSync, rmSync } = await import('node:fs')
  const os = await import('node:os')
  const root = mkdtempSync(join(os.tmpdir(), 'arxa-snap-'))
  try {
    const orgPath = join(root, 'bulk-org')
    mkdirSync(orgPath, { recursive: true }) // D69: scaffold IN PLACE — the folder exists first
    mod.scaffoldOrg(orgPath, 'Snap Org')
    const l2 = mod.createOrgLifecycle({ workspaceRoot: root })
    await l2.openOrg(orgPath, { deferSnapshot: true })
    check('rows-snap: deferred open reports snapshotPending true', l2.current.snapshotPending() === true)
    let guardMsg = ''
    try { await l2.current.newSession('probe', null) } catch (e) { guardMsg = String(e?.message ?? e) }
    check('rows-snap: session creation refuses with a human reason while pending', guardMsg.includes('initial-snapshot-pending'))
    const deadline = Date.now() + 20000
    while (l2.current.snapshotPending() && Date.now() < deadline) await new Promise((r) => setTimeout(r, 100))
    check('rows-snap: detached snapshot lands HEAD; gate lifts itself', l2.current.snapshotPending() === false)
    try { l2.closeOrg() } catch {}
  } finally {
    rmSync(root, { recursive: true, force: true })
  }
}
check('rows face: host-served read-only exports (listSessions/listTrash)', typeof mod?.listSessions === 'function' && typeof mod?.listTrash === 'function')
check('rows face: workspace-root discovery exported', typeof mod?.loadWorkspaceRoot === 'function')

// ---- 8. pendingInteraction producer-consumer wiring (D63) ----------------------
// The producer is dsh itself: client-runtime SessionManager classifies
// question/requested mux frames into SessionSummary.pendingInteraction
// (approval | plan-review | question — 0.1.1-rc.2). The sidebar consumes it
// in three places; regeneration dropping any one silently strands the union
// (rows would never show the waiting pills), so pin all three.
check('wiring: session rows spread pendingInteraction',
  client.includes('...s.pendingInteraction === void 0 ? {} : { pendingInteraction: s.pendingInteraction }'))
check('wiring: search rows spread pendingInteraction',
  client.includes('...summary.pendingInteraction === void 0 ? {} : { pendingInteraction: summary.pendingInteraction }'))
check('wiring: status switch covers the closed union',
  client.includes('case "approval":') && client.includes('case "plan-review":')
  && client.includes('case "question":') && client.includes('assertNever(node.pendingInteraction)'))
check('wiring: runtime producer present (SessionManager pendingInteractions)',
  (() => {
    try {
      const rt = readFileSync(join(repo, 'node_modules', '@deepseek-ai', 'dsh-client-runtime', 'lib', 'client.js'), 'utf8')
      return rt.includes('pendingInteractions') && rt.includes('questionInteractionStatus')
    } catch { return false }
  })())

console.log(failures === 0 ? '\narxa-sidebar selftest: ALL GREEN' : `\narxa-sidebar selftest: ${failures} FAILURE(S)`)
process.exit(failures === 0 ? 0 : 1)
