// Vendor bundle builder — DEV-TIME ONLY (node lib/vendor.js). Bundles the
// pinned viewing libraries into IIFE files under lib/vendor/ that the HOST
// serves on the studio origin (/__arxa/artifacts/vendor/<name>.js) and the
// CLIENT loads as plain <script> tags setting window.ArxaCM / window.ArxaMD.
// The dsh client module graph only resolves declared inject packages, so
// vendored prebuilt bundles are the ADR-0009 "categorized vendored
// libraries" form. Outputs are COMMITTED (same discipline as gen-workspace's
// spliced bundles); rerun after bumping the pinned versions below, and bump
// the plugin version (D77).
//
// Provenance stamped into each bundle header from these pins:
const VERSIONS = {
  esbuild: '0.28.2',
  codemirror: '6.0.2', '@codemirror/view': '6.43.9', '@codemirror/state': '6.7.1',
  '@codemirror/commands': '6.11.0', '@codemirror/language': '6.12.4',
  '@codemirror/search': '6.7.1', '@codemirror/merge': '6.12.2',
  '@codemirror/autocomplete': '6.20.3', '@codemirror/lint': '6.9.7',
  '@codemirror/lang-markdown': '6.5.2', '@codemirror/lang-javascript': '6.2.5',
  '@codemirror/lang-css': '6.3.1', '@codemirror/lang-html': '6.4.12',
  '@codemirror/lang-json': '6.0.2', '@codemirror/lang-yaml': '6.1.3',
  'markdown-it': '15.0.1', dompurify: '3.4.14', 'pdfjs-dist': '6.3.289',
}

import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs'

const here = dirname(fileURLToPath(import.meta.url))
// Sources resolve from the ISOLATED build dir (lib/vendor-build) — see
// vendor-build/package.json for why (root --no-save installs are not
// cumulative and get wiped by the next root npm install).
const buildDir = join(here, 'vendor-build')
const require2 = createRequire(join(buildDir, 'package.json'))
const esbuild = require2('esbuild')
const outDir = join(here, 'vendor')
fs.mkdirSync(outDir, { recursive: true })

const CM_ENTRY = [
  "import { basicSetup, EditorView } from 'codemirror'",
  "import { EditorState } from '@codemirror/state'",
  "import { markdown } from '@codemirror/lang-markdown'",
  "import { javascript } from '@codemirror/lang-javascript'",
  "import { css } from '@codemirror/lang-css'",
  "import { html } from '@codemirror/lang-html'",
  "import { json } from '@codemirror/lang-json'",
  "import { yaml } from '@codemirror/lang-yaml'",
  "import { keymap } from '@codemirror/view'",
  "import { indentWithTab } from '@codemirror/commands'",
  'window.ArxaCM = {',
  '  basicSetup: [basicSetup, keymap.of([indentWithTab])],',
  '  EditorView, EditorState,',
  '  langs: { markdown, javascript, css, html, json, yaml },',
  '}',
].join('\n')

const PDF_ENTRY = [
  "import * as pdfjsLib from 'pdfjs-dist'",
  "pdfjsLib.GlobalWorkerOptions.workerSrc = '/__arxa/artifacts/vendor/pdf.worker.js'",
  'window.ArxaPDF = {',
  '  // Hardened for untrusted documents: no eval path (PDF.js hardening).',
  '  getDocument: (opts) => pdfjsLib.getDocument({ isEvalSupported: false, ...opts }),',
  '}',
].join('\n')

const PDF_WORKER_ENTRY = [
  "import 'pdfjs-dist/build/pdf.worker.mjs'",
].join('\n')

const MD_ENTRY = [
  "import MarkdownIt from 'markdown-it'",
  "import DOMPurify from 'dompurify'",
  'window.ArxaMD = {',
  '  render(mdText) {',
  "    const md = new MarkdownIt({ html: false, linkify: true, breaks: false })",
  '    return DOMPurify.sanitize(md.render(String(mdText)))',
  '  },',
  '}',
].join('\n')

const banner = (name) => '/* arxa-artifact-viewer vendored bundle — GENERATED by lib/vendor.js, do not edit.\n'
  + ' * Pinned sources: ' + JSON.stringify(VERSIONS) + '\n'
  + ' * Rebuild: node plugins/artifact-viewer/lib/vendor.js */\n'

for (const [name, entry, globalName] of [
  ['codemirror', CM_ENTRY, 'ArxaCM'],
  ['markdown', MD_ENTRY, 'ArxaMD'],
  ['pdf', PDF_ENTRY, 'ArxaPDF'],
  ['pdf.worker', PDF_WORKER_ENTRY, null],
]) {
  const out = join(outDir, name + '.js')
  await esbuild.build({
    absWorkingDir: buildDir,
    nodePaths: [join(buildDir, 'node_modules')],
    stdin: { contents: entry, resolveDir: buildDir, sourcefile: name + '-entry.js' },
    bundle: true, minify: true, format: 'iife', target: ['es2020'],
    outfile: out, banner: { js: banner(name) }, logLevel: 'silent',
  })
  const size = fs.statSync(out).size
  console.log('vendored ' + name + '.js -> ' + out + ' (' + size + ' bytes, sets window.' + globalName + ')')
}
